// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertFlag = `-- name: InsertFlag :batchexec
INSERT INTO flag (id, tenant_id, outlet_id, device_id, event_id, target_type, target_id, code, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertFlagBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertFlagParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	OutletID   uuid.UUID
	DeviceID   uuid.UUID
	EventID    uuid.UUID
	TargetType string
	TargetID   uuid.UUID
	Code       string
	Detail     []byte
}

func (q *Queries) InsertFlag(ctx context.Context, arg []InsertFlagParams) *InsertFlagBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.TenantID,
			a.OutletID,
			a.DeviceID,
			a.EventID,
			a.TargetType,
			a.TargetID,
			a.Code,
			a.Detail,
		}
		batch.Queue(insertFlag, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertFlagBatchResults{br, len(arg), false}
}

func (b *InsertFlagBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertFlagBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertPayment = `-- name: InsertPayment :batchexec
INSERT INTO payment (id, tenant_id, sale_id, method, amount, tendered, change, reference)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPaymentBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPaymentParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	SaleID    uuid.UUID
	Method    string
	Amount    int64
	Tendered  *int64
	Change    *int64
	Reference string
}

func (q *Queries) InsertPayment(ctx context.Context, arg []InsertPaymentParams) *InsertPaymentBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.TenantID,
			a.SaleID,
			a.Method,
			a.Amount,
			a.Tendered,
			a.Change,
			a.Reference,
		}
		batch.Queue(insertPayment, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPaymentBatchResults{br, len(arg), false}
}

func (b *InsertPaymentBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPaymentBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertSaleDiscount = `-- name: InsertSaleDiscount :batchexec
INSERT INTO sale_discount (id, tenant_id, sale_id, sale_line_id, kind, value, amount, reason, approved_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertSaleDiscountBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertSaleDiscountParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	SaleID     uuid.UUID
	SaleLineID *uuid.UUID
	Kind       string
	Value      int64
	Amount     int64
	Reason     string
	ApprovedBy *uuid.UUID
}

func (q *Queries) InsertSaleDiscount(ctx context.Context, arg []InsertSaleDiscountParams) *InsertSaleDiscountBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.TenantID,
			a.SaleID,
			a.SaleLineID,
			a.Kind,
			a.Value,
			a.Amount,
			a.Reason,
			a.ApprovedBy,
		}
		batch.Queue(insertSaleDiscount, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertSaleDiscountBatchResults{br, len(arg), false}
}

func (b *InsertSaleDiscountBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertSaleDiscountBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertSaleLine = `-- name: InsertSaleLine :batchexec
INSERT INTO sale_line (id, tenant_id, sale_id, line_no, variant_id, name_snapshot, unit_price, quantity, line_discount,
                       allocated_bill_discount, line_total)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11)
`

type InsertSaleLineBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertSaleLineParams struct {
	ID                    uuid.UUID
	TenantID              uuid.UUID
	SaleID                uuid.UUID
	LineNo                int32
	VariantID             uuid.UUID
	NameSnapshot          string
	UnitPrice             int64
	Quantity              int32
	LineDiscount          int64
	AllocatedBillDiscount int64
	LineTotal             int64
}

func (q *Queries) InsertSaleLine(ctx context.Context, arg []InsertSaleLineParams) *InsertSaleLineBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.TenantID,
			a.SaleID,
			a.LineNo,
			a.VariantID,
			a.NameSnapshot,
			a.UnitPrice,
			a.Quantity,
			a.LineDiscount,
			a.AllocatedBillDiscount,
			a.LineTotal,
		}
		batch.Queue(insertSaleLine, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertSaleLineBatchResults{br, len(arg), false}
}

func (b *InsertSaleLineBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertSaleLineBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertSaleLineModifier = `-- name: InsertSaleLineModifier :batchexec
INSERT INTO sale_line_modifier (tenant_id, sale_line_id, position, modifier_id, name_snapshot, price_delta)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSaleLineModifierBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertSaleLineModifierParams struct {
	TenantID     uuid.UUID
	SaleLineID   uuid.UUID
	Position     int32
	ModifierID   uuid.UUID
	NameSnapshot string
	PriceDelta   int64
}

func (q *Queries) InsertSaleLineModifier(ctx context.Context, arg []InsertSaleLineModifierParams) *InsertSaleLineModifierBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TenantID,
			a.SaleLineID,
			a.Position,
			a.ModifierID,
			a.NameSnapshot,
			a.PriceDelta,
		}
		batch.Queue(insertSaleLineModifier, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertSaleLineModifierBatchResults{br, len(arg), false}
}

func (b *InsertSaleLineModifierBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertSaleLineModifierBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
