// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeShift = `-- name: CloseShift :execrows
UPDATE shift SET closed_by = $1, closed_at = $2, counted_cash = $3, close_event_id = $4
WHERE tenant_id = $5 AND id = $6 AND closed_at IS NULL
`

type CloseShiftParams struct {
	ClosedBy     *uuid.UUID
	ClosedAt     *time.Time
	CountedCash  *int64
	CloseEventID *uuid.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeShift,
		arg.ClosedBy,
		arg.ClosedAt,
		arg.CountedCash,
		arg.CloseEventID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSaleForVoid = `-- name: GetSaleForVoid :one

SELECT id, outlet_id, shift_id, status FROM sale WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetSaleForVoidParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetSaleForVoidRow struct {
	ID       uuid.UUID
	OutletID uuid.UUID
	ShiftID  uuid.UUID
	Status   string
}

// Voids
func (q *Queries) GetSaleForVoid(ctx context.Context, arg GetSaleForVoidParams) (GetSaleForVoidRow, error) {
	row := q.db.QueryRow(ctx, getSaleForVoid, arg.TenantID, arg.ID)
	var i GetSaleForVoidRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.ShiftID,
		&i.Status,
	)
	return i, err
}

const getShift = `-- name: GetShift :one
SELECT id, tenant_id, outlet_id, device_id, opened_by, opened_at, opening_cash, business_date, received_at, closed_by, closed_at, counted_cash, close_event_id FROM shift WHERE tenant_id = $1 AND id = $2
`

type GetShiftParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetShift(ctx context.Context, arg GetShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, getShift, arg.TenantID, arg.ID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.DeviceID,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.OpeningCash,
		&i.BusinessDate,
		&i.ReceivedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CountedCash,
		&i.CloseEventID,
	)
	return i, err
}

const getShiftForUpdate = `-- name: GetShiftForUpdate :one
SELECT id, tenant_id, outlet_id, device_id, opened_by, opened_at, opening_cash, business_date, received_at, closed_by, closed_at, counted_cash, close_event_id FROM shift WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetShiftForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetShiftForUpdate(ctx context.Context, arg GetShiftForUpdateParams) (Shift, error) {
	row := q.db.QueryRow(ctx, getShiftForUpdate, arg.TenantID, arg.ID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.DeviceID,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.OpeningCash,
		&i.BusinessDate,
		&i.ReceivedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CountedCash,
		&i.CloseEventID,
	)
	return i, err
}

const insertCashMovement = `-- name: InsertCashMovement :exec
INSERT INTO cash_movement (id, tenant_id, outlet_id, shift_id, kind, amount, reason, staff_id, device_time, received_at, business_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertCashMovementParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	ShiftID      uuid.UUID
	Kind         string
	Amount       int64
	Reason       string
	StaffID      uuid.UUID
	DeviceTime   time.Time
	ReceivedAt   time.Time
	BusinessDate pgtype.Date
}

func (q *Queries) InsertCashMovement(ctx context.Context, arg InsertCashMovementParams) error {
	_, err := q.db.Exec(ctx, insertCashMovement,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.ShiftID,
		arg.Kind,
		arg.Amount,
		arg.Reason,
		arg.StaffID,
		arg.DeviceTime,
		arg.ReceivedAt,
		arg.BusinessDate,
	)
	return err
}

const insertSale = `-- name: InsertSale :exec

INSERT INTO sale (id, tenant_id, outlet_id, device_id, shift_id, staff_id, receipt_number, receipt_device_code, receipt_counter,
                  device_time, received_at, business_date, pricing_version, pricing, catalog_seq, subtotal, discount_total,
                  service_charge, tax, tax_included, rounding_amount, total)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14, $15, $16, $17,
        $18, $19, $20, $21, $22)
`

type InsertSaleParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	OutletID          uuid.UUID
	DeviceID          uuid.UUID
	ShiftID           uuid.UUID
	StaffID           uuid.UUID
	ReceiptNumber     string
	ReceiptDeviceCode int32
	ReceiptCounter    int64
	DeviceTime        time.Time
	ReceivedAt        time.Time
	BusinessDate      pgtype.Date
	PricingVersion    int32
	Pricing           []byte
	CatalogSeq        int64
	Subtotal          int64
	DiscountTotal     int64
	ServiceCharge     int64
	Tax               int64
	TaxIncluded       bool
	RoundingAmount    int64
	Total             int64
}

// Sales
func (q *Queries) InsertSale(ctx context.Context, arg InsertSaleParams) error {
	_, err := q.db.Exec(ctx, insertSale,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.DeviceID,
		arg.ShiftID,
		arg.StaffID,
		arg.ReceiptNumber,
		arg.ReceiptDeviceCode,
		arg.ReceiptCounter,
		arg.DeviceTime,
		arg.ReceivedAt,
		arg.BusinessDate,
		arg.PricingVersion,
		arg.Pricing,
		arg.CatalogSeq,
		arg.Subtotal,
		arg.DiscountTotal,
		arg.ServiceCharge,
		arg.Tax,
		arg.TaxIncluded,
		arg.RoundingAmount,
		arg.Total,
	)
	return err
}

const insertShift = `-- name: InsertShift :exec

INSERT INTO shift (id, tenant_id, outlet_id, device_id, opened_by, opened_at, opening_cash, business_date, received_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertShiftParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	DeviceID     uuid.UUID
	OpenedBy     uuid.UUID
	OpenedAt     time.Time
	OpeningCash  int64
	BusinessDate pgtype.Date
	ReceivedAt   time.Time
}

// Shifts
func (q *Queries) InsertShift(ctx context.Context, arg InsertShiftParams) error {
	_, err := q.db.Exec(ctx, insertShift,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.DeviceID,
		arg.OpenedBy,
		arg.OpenedAt,
		arg.OpeningCash,
		arg.BusinessDate,
		arg.ReceivedAt,
	)
	return err
}

const insertVoid = `-- name: InsertVoid :exec
INSERT INTO void (id, tenant_id, outlet_id, sale_id, shift_id, staff_id, approved_by, reason, device_time, received_at, business_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertVoidParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	SaleID       uuid.UUID
	ShiftID      uuid.UUID
	StaffID      uuid.UUID
	ApprovedBy   *uuid.UUID
	Reason       string
	DeviceTime   time.Time
	ReceivedAt   time.Time
	BusinessDate pgtype.Date
}

func (q *Queries) InsertVoid(ctx context.Context, arg InsertVoidParams) error {
	_, err := q.db.Exec(ctx, insertVoid,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.SaleID,
		arg.ShiftID,
		arg.StaffID,
		arg.ApprovedBy,
		arg.Reason,
		arg.DeviceTime,
		arg.ReceivedAt,
		arg.BusinessDate,
	)
	return err
}

const markSaleVoided = `-- name: MarkSaleVoided :exec
UPDATE sale SET status = 'voided' WHERE tenant_id = $1 AND id = $2 AND status = 'completed'
`

type MarkSaleVoidedParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) MarkSaleVoided(ctx context.Context, arg MarkSaleVoidedParams) error {
	_, err := q.db.Exec(ctx, markSaleVoided, arg.TenantID, arg.ID)
	return err
}
