// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeShift = `-- name: CloseShift :execrows
UPDATE shift SET closed_by = $1, closed_at = $2, counted_cash = $3, close_event_id = $4
WHERE tenant_id = $5 AND id = $6 AND closed_at IS NULL
`

type CloseShiftParams struct {
	ClosedBy     *uuid.UUID
	ClosedAt     *time.Time
	CountedCash  *int64
	CloseEventID *uuid.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeShift,
		arg.ClosedBy,
		arg.ClosedAt,
		arg.CountedCash,
		arg.CloseEventID,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSale = `-- name: GetSale :one
SELECT id, tenant_id, outlet_id, device_id, shift_id, staff_id, receipt_number, receipt_device_code, receipt_counter, device_time, received_at, business_date, pricing_version, pricing, catalog_seq, subtotal, discount_total, service_charge, tax, tax_included, rounding_amount, total, status FROM sale WHERE tenant_id = $1 AND id = $2
`

type GetSaleParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetSale(ctx context.Context, arg GetSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, getSale, arg.TenantID, arg.ID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.DeviceID,
		&i.ShiftID,
		&i.StaffID,
		&i.ReceiptNumber,
		&i.ReceiptDeviceCode,
		&i.ReceiptCounter,
		&i.DeviceTime,
		&i.ReceivedAt,
		&i.BusinessDate,
		&i.PricingVersion,
		&i.Pricing,
		&i.CatalogSeq,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ServiceCharge,
		&i.Tax,
		&i.TaxIncluded,
		&i.RoundingAmount,
		&i.Total,
		&i.Status,
	)
	return i, err
}

const getSaleForRefund = `-- name: GetSaleForRefund :one

SELECT id, outlet_id, status, total, rounding_amount FROM sale WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetSaleForRefundParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetSaleForRefundRow struct {
	ID             uuid.UUID
	OutletID       uuid.UUID
	Status         string
	Total          int64
	RoundingAmount int64
}

// Refunds (refund.go).
// Locks the sale, so two refunds of it check their caps one after the other.
func (q *Queries) GetSaleForRefund(ctx context.Context, arg GetSaleForRefundParams) (GetSaleForRefundRow, error) {
	row := q.db.QueryRow(ctx, getSaleForRefund, arg.TenantID, arg.ID)
	var i GetSaleForRefundRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.Status,
		&i.Total,
		&i.RoundingAmount,
	)
	return i, err
}

const getSaleForVoid = `-- name: GetSaleForVoid :one

SELECT id, outlet_id, shift_id, status FROM sale WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetSaleForVoidParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetSaleForVoidRow struct {
	ID       uuid.UUID
	OutletID uuid.UUID
	ShiftID  uuid.UUID
	Status   string
}

// Voids
func (q *Queries) GetSaleForVoid(ctx context.Context, arg GetSaleForVoidParams) (GetSaleForVoidRow, error) {
	row := q.db.QueryRow(ctx, getSaleForVoid, arg.TenantID, arg.ID)
	var i GetSaleForVoidRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.ShiftID,
		&i.Status,
	)
	return i, err
}

const getShift = `-- name: GetShift :one
SELECT id, tenant_id, outlet_id, device_id, opened_by, opened_at, opening_cash, business_date, received_at, closed_by, closed_at, counted_cash, close_event_id FROM shift WHERE tenant_id = $1 AND id = $2
`

type GetShiftParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetShift(ctx context.Context, arg GetShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, getShift, arg.TenantID, arg.ID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.DeviceID,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.OpeningCash,
		&i.BusinessDate,
		&i.ReceivedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CountedCash,
		&i.CloseEventID,
	)
	return i, err
}

const getShiftForUpdate = `-- name: GetShiftForUpdate :one
SELECT id, tenant_id, outlet_id, device_id, opened_by, opened_at, opening_cash, business_date, received_at, closed_by, closed_at, counted_cash, close_event_id FROM shift WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetShiftForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetShiftForUpdate(ctx context.Context, arg GetShiftForUpdateParams) (Shift, error) {
	row := q.db.QueryRow(ctx, getShiftForUpdate, arg.TenantID, arg.ID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.DeviceID,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.OpeningCash,
		&i.BusinessDate,
		&i.ReceivedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CountedCash,
		&i.CloseEventID,
	)
	return i, err
}

const getVoidOfSale = `-- name: GetVoidOfSale :one
SELECT id, tenant_id, outlet_id, sale_id, shift_id, staff_id, approved_by, reason, device_time, received_at, business_date FROM void WHERE tenant_id = $1 AND sale_id = $2
`

type GetVoidOfSaleParams struct {
	TenantID uuid.UUID
	SaleID   uuid.UUID
}

func (q *Queries) GetVoidOfSale(ctx context.Context, arg GetVoidOfSaleParams) (Void, error) {
	row := q.db.QueryRow(ctx, getVoidOfSale, arg.TenantID, arg.SaleID)
	var i Void
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.SaleID,
		&i.ShiftID,
		&i.StaffID,
		&i.ApprovedBy,
		&i.Reason,
		&i.DeviceTime,
		&i.ReceivedAt,
		&i.BusinessDate,
	)
	return i, err
}

const insertCashMovement = `-- name: InsertCashMovement :exec
INSERT INTO cash_movement (id, tenant_id, outlet_id, shift_id, kind, amount, reason, staff_id, device_time, received_at, business_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertCashMovementParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	ShiftID      uuid.UUID
	Kind         string
	Amount       int64
	Reason       string
	StaffID      uuid.UUID
	DeviceTime   time.Time
	ReceivedAt   time.Time
	BusinessDate pgtype.Date
}

func (q *Queries) InsertCashMovement(ctx context.Context, arg InsertCashMovementParams) error {
	_, err := q.db.Exec(ctx, insertCashMovement,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.ShiftID,
		arg.Kind,
		arg.Amount,
		arg.Reason,
		arg.StaffID,
		arg.DeviceTime,
		arg.ReceivedAt,
		arg.BusinessDate,
	)
	return err
}

const insertRefund = `-- name: InsertRefund :exec
INSERT INTO refund (id, tenant_id, outlet_id, sale_id, shift_id, staff_id, approved_by, method, amount, reason, device_time, received_at, business_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertRefundParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	SaleID       uuid.UUID
	ShiftID      uuid.UUID
	StaffID      uuid.UUID
	ApprovedBy   *uuid.UUID
	Method       string
	Amount       int64
	Reason       string
	DeviceTime   time.Time
	ReceivedAt   time.Time
	BusinessDate pgtype.Date
}

func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) error {
	_, err := q.db.Exec(ctx, insertRefund,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.SaleID,
		arg.ShiftID,
		arg.StaffID,
		arg.ApprovedBy,
		arg.Method,
		arg.Amount,
		arg.Reason,
		arg.DeviceTime,
		arg.ReceivedAt,
		arg.BusinessDate,
	)
	return err
}

const insertRefundLines = `-- name: InsertRefundLines :exec
INSERT INTO refund_line (tenant_id, refund_id, sale_line_id, quantity, amount)
SELECT $1::uuid, $2::uuid, a.sale_line_id, b.quantity, c.amount
FROM unnest($3::uuid[]) WITH ORDINALITY AS a(sale_line_id, n)
JOIN unnest($4::integer[]) WITH ORDINALITY AS b(quantity, n) ON b.n = a.n
JOIN unnest($5::bigint[]) WITH ORDINALITY AS c(amount, n) ON c.n = a.n
`

type InsertRefundLinesParams struct {
	TenantID    uuid.UUID
	RefundID    uuid.UUID
	SaleLineIds []uuid.UUID
	Quantities  []int32
	Amounts     []int64
}

func (q *Queries) InsertRefundLines(ctx context.Context, arg InsertRefundLinesParams) error {
	_, err := q.db.Exec(ctx, insertRefundLines,
		arg.TenantID,
		arg.RefundID,
		arg.SaleLineIds,
		arg.Quantities,
		arg.Amounts,
	)
	return err
}

const insertSale = `-- name: InsertSale :exec

INSERT INTO sale (id, tenant_id, outlet_id, device_id, shift_id, staff_id, receipt_number, receipt_device_code, receipt_counter,
                  device_time, received_at, business_date, pricing_version, pricing, catalog_seq, subtotal, discount_total,
                  service_charge, tax, tax_included, rounding_amount, total)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14, $15, $16, $17,
        $18, $19, $20, $21, $22)
`

type InsertSaleParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	OutletID          uuid.UUID
	DeviceID          uuid.UUID
	ShiftID           uuid.UUID
	StaffID           uuid.UUID
	ReceiptNumber     string
	ReceiptDeviceCode int32
	ReceiptCounter    int64
	DeviceTime        time.Time
	ReceivedAt        time.Time
	BusinessDate      pgtype.Date
	PricingVersion    int32
	Pricing           []byte
	CatalogSeq        int64
	Subtotal          int64
	DiscountTotal     int64
	ServiceCharge     int64
	Tax               int64
	TaxIncluded       bool
	RoundingAmount    int64
	Total             int64
}

// Sales
func (q *Queries) InsertSale(ctx context.Context, arg InsertSaleParams) error {
	_, err := q.db.Exec(ctx, insertSale,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.DeviceID,
		arg.ShiftID,
		arg.StaffID,
		arg.ReceiptNumber,
		arg.ReceiptDeviceCode,
		arg.ReceiptCounter,
		arg.DeviceTime,
		arg.ReceivedAt,
		arg.BusinessDate,
		arg.PricingVersion,
		arg.Pricing,
		arg.CatalogSeq,
		arg.Subtotal,
		arg.DiscountTotal,
		arg.ServiceCharge,
		arg.Tax,
		arg.TaxIncluded,
		arg.RoundingAmount,
		arg.Total,
	)
	return err
}

const insertShift = `-- name: InsertShift :exec

INSERT INTO shift (id, tenant_id, outlet_id, device_id, opened_by, opened_at, opening_cash, business_date, received_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertShiftParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	DeviceID     uuid.UUID
	OpenedBy     uuid.UUID
	OpenedAt     time.Time
	OpeningCash  int64
	BusinessDate pgtype.Date
	ReceivedAt   time.Time
}

// Shifts
func (q *Queries) InsertShift(ctx context.Context, arg InsertShiftParams) error {
	_, err := q.db.Exec(ctx, insertShift,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.DeviceID,
		arg.OpenedBy,
		arg.OpenedAt,
		arg.OpeningCash,
		arg.BusinessDate,
		arg.ReceivedAt,
	)
	return err
}

const insertVoid = `-- name: InsertVoid :exec
INSERT INTO void (id, tenant_id, outlet_id, sale_id, shift_id, staff_id, approved_by, reason, device_time, received_at, business_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertVoidParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	SaleID       uuid.UUID
	ShiftID      uuid.UUID
	StaffID      uuid.UUID
	ApprovedBy   *uuid.UUID
	Reason       string
	DeviceTime   time.Time
	ReceivedAt   time.Time
	BusinessDate pgtype.Date
}

func (q *Queries) InsertVoid(ctx context.Context, arg InsertVoidParams) error {
	_, err := q.db.Exec(ctx, insertVoid,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.SaleID,
		arg.ShiftID,
		arg.StaffID,
		arg.ApprovedBy,
		arg.Reason,
		arg.DeviceTime,
		arg.ReceivedAt,
		arg.BusinessDate,
	)
	return err
}

const listFlagsBySales = `-- name: ListFlagsBySales :many
SELECT f.id, f.code, f.target_type, f.target_id, f.detail, f.created_at, coalesce(v.sale_id, r.sale_id, f.target_id)::uuid AS sale_id
FROM flag f
LEFT JOIN void v ON v.tenant_id = f.tenant_id AND v.id = f.target_id AND f.target_type = 'void'
LEFT JOIN refund r ON r.tenant_id = f.tenant_id AND r.id = f.target_id AND f.target_type = 'refund'
WHERE f.tenant_id = $1
  AND (f.target_id = ANY($2::uuid[]) OR v.sale_id = ANY($2::uuid[]) OR r.sale_id = ANY($2::uuid[]))
ORDER BY f.created_at, f.id
`

type ListFlagsBySalesParams struct {
	TenantID uuid.UUID
	SaleIds  []uuid.UUID
}

type ListFlagsBySalesRow struct {
	ID         uuid.UUID
	Code       string
	TargetType string
	TargetID   uuid.UUID
	Detail     []byte
	CreatedAt  time.Time
	SaleID     uuid.UUID
}

// The flags about each sale, its void and its refunds, in one query.
func (q *Queries) ListFlagsBySales(ctx context.Context, arg ListFlagsBySalesParams) ([]ListFlagsBySalesRow, error) {
	rows, err := q.db.Query(ctx, listFlagsBySales, arg.TenantID, arg.SaleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlagsBySalesRow
	for rows.Next() {
		var i ListFlagsBySalesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
			&i.SaleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsBySales = `-- name: ListPaymentsBySales :many
SELECT id, sale_id, method, amount, tendered, change, reference, status FROM payment
WHERE tenant_id = $1 AND sale_id = ANY($2::uuid[])
ORDER BY sale_id, id
`

type ListPaymentsBySalesParams struct {
	TenantID uuid.UUID
	SaleIds  []uuid.UUID
}

type ListPaymentsBySalesRow struct {
	ID        uuid.UUID
	SaleID    uuid.UUID
	Method    string
	Amount    int64
	Tendered  *int64
	Change    *int64
	Reference string
	Status    string
}

func (q *Queries) ListPaymentsBySales(ctx context.Context, arg ListPaymentsBySalesParams) ([]ListPaymentsBySalesRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsBySales, arg.TenantID, arg.SaleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsBySalesRow
	for rows.Next() {
		var i ListPaymentsBySalesRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.Method,
			&i.Amount,
			&i.Tendered,
			&i.Change,
			&i.Reference,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundLinesOfSale = `-- name: ListRefundLinesOfSale :many
SELECT rl.refund_id, l.line_no, rl.quantity, rl.amount
FROM refund r
JOIN refund_line rl ON rl.tenant_id = r.tenant_id AND rl.refund_id = r.id
JOIN sale_line l ON l.tenant_id = rl.tenant_id AND l.id = rl.sale_line_id
WHERE r.tenant_id = $1 AND r.sale_id = $2
ORDER BY rl.refund_id, l.line_no
`

type ListRefundLinesOfSaleParams struct {
	TenantID uuid.UUID
	SaleID   uuid.UUID
}

type ListRefundLinesOfSaleRow struct {
	RefundID uuid.UUID
	LineNo   int32
	Quantity int32
	Amount   int64
}

func (q *Queries) ListRefundLinesOfSale(ctx context.Context, arg ListRefundLinesOfSaleParams) ([]ListRefundLinesOfSaleRow, error) {
	rows, err := q.db.Query(ctx, listRefundLinesOfSale, arg.TenantID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefundLinesOfSaleRow
	for rows.Next() {
		var i ListRefundLinesOfSaleRow
		if err := rows.Scan(
			&i.RefundID,
			&i.LineNo,
			&i.Quantity,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsOfSale = `-- name: ListRefundsOfSale :many
SELECT r.id, r.shift_id, r.staff_id, r.approved_by, r.method, r.amount, r.reason, r.device_time, r.received_at, r.business_date
FROM refund r WHERE r.tenant_id = $1 AND r.sale_id = $2
ORDER BY r.device_time, r.id
`

type ListRefundsOfSaleParams struct {
	TenantID uuid.UUID
	SaleID   uuid.UUID
}

type ListRefundsOfSaleRow struct {
	ID           uuid.UUID
	ShiftID      uuid.UUID
	StaffID      uuid.UUID
	ApprovedBy   *uuid.UUID
	Method       string
	Amount       int64
	Reason       string
	DeviceTime   time.Time
	ReceivedAt   time.Time
	BusinessDate pgtype.Date
}

func (q *Queries) ListRefundsOfSale(ctx context.Context, arg ListRefundsOfSaleParams) ([]ListRefundsOfSaleRow, error) {
	rows, err := q.db.Query(ctx, listRefundsOfSale, arg.TenantID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefundsOfSaleRow
	for rows.Next() {
		var i ListRefundsOfSaleRow
		if err := rows.Scan(
			&i.ID,
			&i.ShiftID,
			&i.StaffID,
			&i.ApprovedBy,
			&i.Method,
			&i.Amount,
			&i.Reason,
			&i.DeviceTime,
			&i.ReceivedAt,
			&i.BusinessDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleDiscounts = `-- name: ListSaleDiscounts :many
SELECT d.id, d.sale_line_id, l.line_no AS line_no, d.kind, d.value, d.amount, d.reason, d.approved_by
FROM sale_discount d
LEFT JOIN sale_line l ON l.tenant_id = d.tenant_id AND l.id = d.sale_line_id
WHERE d.tenant_id = $1 AND d.sale_id = $2
ORDER BY d.id
`

type ListSaleDiscountsParams struct {
	TenantID uuid.UUID
	SaleID   uuid.UUID
}

type ListSaleDiscountsRow struct {
	ID         uuid.UUID
	SaleLineID *uuid.UUID
	LineNo     *int32
	Kind       string
	Value      int64
	Amount     int64
	Reason     string
	ApprovedBy *uuid.UUID
}

func (q *Queries) ListSaleDiscounts(ctx context.Context, arg ListSaleDiscountsParams) ([]ListSaleDiscountsRow, error) {
	rows, err := q.db.Query(ctx, listSaleDiscounts, arg.TenantID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSaleDiscountsRow
	for rows.Next() {
		var i ListSaleDiscountsRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleLineID,
			&i.LineNo,
			&i.Kind,
			&i.Value,
			&i.Amount,
			&i.Reason,
			&i.ApprovedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleLineModifiers = `-- name: ListSaleLineModifiers :many
SELECT m.tenant_id, m.sale_line_id, m.position, m.modifier_id, m.name_snapshot, m.price_delta FROM sale_line_modifier m
JOIN sale_line l ON l.tenant_id = m.tenant_id AND l.id = m.sale_line_id
WHERE l.tenant_id = $1 AND l.sale_id = $2
ORDER BY l.line_no, m.position
`

type ListSaleLineModifiersParams struct {
	TenantID uuid.UUID
	SaleID   uuid.UUID
}

func (q *Queries) ListSaleLineModifiers(ctx context.Context, arg ListSaleLineModifiersParams) ([]SaleLineModifier, error) {
	rows, err := q.db.Query(ctx, listSaleLineModifiers, arg.TenantID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleLineModifier
	for rows.Next() {
		var i SaleLineModifier
		if err := rows.Scan(
			&i.TenantID,
			&i.SaleLineID,
			&i.Position,
			&i.ModifierID,
			&i.NameSnapshot,
			&i.PriceDelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleLines = `-- name: ListSaleLines :many
SELECT id, tenant_id, sale_id, line_no, variant_id, name_snapshot, unit_price, quantity, line_discount, allocated_bill_discount, line_total FROM sale_line WHERE tenant_id = $1 AND sale_id = $2 ORDER BY line_no
`

type ListSaleLinesParams struct {
	TenantID uuid.UUID
	SaleID   uuid.UUID
}

func (q *Queries) ListSaleLines(ctx context.Context, arg ListSaleLinesParams) ([]SaleLine, error) {
	rows, err := q.db.Query(ctx, listSaleLines, arg.TenantID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleLine
	for rows.Next() {
		var i SaleLine
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SaleID,
			&i.LineNo,
			&i.VariantID,
			&i.NameSnapshot,
			&i.UnitPrice,
			&i.Quantity,
			&i.LineDiscount,
			&i.AllocatedBillDiscount,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many

SELECT s.id, s.outlet_id, s.device_id, s.shift_id, s.staff_id, s.receipt_number, s.device_time, s.received_at, s.business_date,
       s.status, s.subtotal, s.discount_total, s.service_charge, s.tax, s.tax_included, s.rounding_amount, s.total,
       coalesce((SELECT sum(r.amount) FROM refund r WHERE r.tenant_id = s.tenant_id AND r.sale_id = s.id), 0)::bigint AS refunded
FROM sale s
WHERE s.tenant_id = $1
  AND ($2::uuid[] IS NULL OR s.outlet_id = ANY($2::uuid[]))
  AND ($3::date IS NULL OR s.business_date >= $3::date)
  AND ($4::date IS NULL OR s.business_date <= $4::date)
  AND ($5::text IS NULL OR s.status = $5::text)
  AND ($6::text IS NULL OR s.receipt_number = $6::text)
  AND ($7::uuid IS NULL OR s.staff_id = $7::uuid)
  AND (NOT $8::boolean OR EXISTS (
        SELECT 1 FROM flag f WHERE f.tenant_id = s.tenant_id AND f.target_id = s.id
        UNION ALL
        SELECT 1 FROM flag f JOIN void v ON v.tenant_id = f.tenant_id AND v.id = f.target_id
        WHERE f.tenant_id = s.tenant_id AND v.sale_id = s.id
        UNION ALL
        SELECT 1 FROM flag f JOIN refund r ON r.tenant_id = f.tenant_id AND r.id = f.target_id
        WHERE f.tenant_id = s.tenant_id AND r.sale_id = s.id))
  AND ($9::date IS NULL OR (s.business_date, s.device_time, s.id) < ($9::date, $10::timestamptz, $11::uuid))
ORDER BY s.business_date DESC, s.device_time DESC, s.id DESC
LIMIT $12
`

type ListSalesParams struct {
	TenantID      uuid.UUID
	OutletIds     []uuid.UUID
	FromDate      pgtype.Date
	ToDate        pgtype.Date
	Status        *string
	ReceiptNumber *string
	StaffID       *uuid.UUID
	FlaggedOnly   bool
	AfterDate     pgtype.Date
	AfterTime     *time.Time
	AfterID       *uuid.UUID
	PageSize      int32
}

type ListSalesRow struct {
	ID             uuid.UUID
	OutletID       uuid.UUID
	DeviceID       uuid.UUID
	ShiftID        uuid.UUID
	StaffID        uuid.UUID
	ReceiptNumber  string
	DeviceTime     time.Time
	ReceivedAt     time.Time
	BusinessDate   pgtype.Date
	Status         string
	Subtotal       int64
	DiscountTotal  int64
	ServiceCharge  int64
	Tax            int64
	TaxIncluded    bool
	RoundingAmount int64
	Total          int64
	Refunded       int64
}

// The back-office sales list and detail (read-only).
// Newest business day first, then newest sale by the device's clock, keyset-paged by
// (business_date, device_time, id). outlet_ids NULL means every outlet.
func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales,
		arg.TenantID,
		arg.OutletIds,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
		arg.ReceiptNumber,
		arg.StaffID,
		arg.FlaggedOnly,
		arg.AfterDate,
		arg.AfterTime,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesRow
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.DeviceID,
			&i.ShiftID,
			&i.StaffID,
			&i.ReceiptNumber,
			&i.DeviceTime,
			&i.ReceivedAt,
			&i.BusinessDate,
			&i.Status,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.ServiceCharge,
			&i.Tax,
			&i.TaxIncluded,
			&i.RoundingAmount,
			&i.Total,
			&i.Refunded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSaleVoided = `-- name: MarkSaleVoided :exec
UPDATE sale SET status = 'voided' WHERE tenant_id = $1 AND id = $2 AND status = 'completed'
`

type MarkSaleVoidedParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) MarkSaleVoided(ctx context.Context, arg MarkSaleVoidedParams) error {
	_, err := q.db.Exec(ctx, markSaleVoided, arg.TenantID, arg.ID)
	return err
}

const saleLinesForRefund = `-- name: SaleLinesForRefund :many
SELECT l.id, l.line_no, l.quantity,
       coalesce((SELECT sum(rl.quantity) FROM refund_line rl WHERE rl.tenant_id = l.tenant_id AND rl.sale_line_id = l.id), 0)::bigint AS refunded
FROM sale_line l
WHERE l.tenant_id = $1 AND l.sale_id = $2
ORDER BY l.line_no
`

type SaleLinesForRefundParams struct {
	TenantID uuid.UUID
	SaleID   uuid.UUID
}

type SaleLinesForRefundRow struct {
	ID       uuid.UUID
	LineNo   int32
	Quantity int32
	Refunded int64
}

// Each line of the sale with how much of it earlier refunds already gave back.
func (q *Queries) SaleLinesForRefund(ctx context.Context, arg SaleLinesForRefundParams) ([]SaleLinesForRefundRow, error) {
	rows, err := q.db.Query(ctx, saleLinesForRefund, arg.TenantID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaleLinesForRefundRow
	for rows.Next() {
		var i SaleLinesForRefundRow
		if err := rows.Scan(
			&i.ID,
			&i.LineNo,
			&i.Quantity,
			&i.Refunded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saleRefundedTotal = `-- name: SaleRefundedTotal :one
SELECT coalesce(sum(amount), 0)::bigint FROM refund WHERE tenant_id = $1 AND sale_id = $2
`

type SaleRefundedTotalParams struct {
	TenantID uuid.UUID
	SaleID   uuid.UUID
}

func (q *Queries) SaleRefundedTotal(ctx context.Context, arg SaleRefundedTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, saleRefundedTotal, arg.TenantID, arg.SaleID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
