// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const advanceTOTP = `-- name: AdvanceTOTP :exec
UPDATE operator SET totp_last_step = $1, totp_confirmed_at = coalesce(totp_confirmed_at, $2::timestamptz)
WHERE id = $3
`

type AdvanceTOTPParams struct {
	Step int64
	Now  time.Time
	ID   uuid.UUID
}

// Records the accepted time step and confirms enrolment on the first success.
func (q *Queries) AdvanceTOTP(ctx context.Context, arg AdvanceTOTPParams) error {
	_, err := q.db.Exec(ctx, advanceTOTP, arg.Step, arg.Now, arg.ID)
	return err
}

const countOperators = `-- name: CountOperators :one
SELECT count(*) FROM operator
`

func (q *Queries) CountOperators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOperators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOperator = `-- name: GetOperator :one
SELECT id, email, password_hash, totp_secret_enc, totp_confirmed_at, totp_last_step, disabled_at, created_at, updated_at FROM operator WHERE id = $1
`

func (q *Queries) GetOperator(ctx context.Context, id uuid.UUID) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperator, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.TotpConfirmedAt,
		&i.TotpLastStep,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorByEmail = `-- name: GetOperatorByEmail :one
SELECT id, email, password_hash, totp_secret_enc, totp_confirmed_at, totp_last_step, disabled_at, created_at, updated_at FROM operator WHERE email = $1
`

func (q *Queries) GetOperatorByEmail(ctx context.Context, email string) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorByEmail, email)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.TotpConfirmedAt,
		&i.TotpLastStep,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorForUpdate = `-- name: GetOperatorForUpdate :one
SELECT id, email, password_hash, totp_secret_enc, totp_confirmed_at, totp_last_step, disabled_at, created_at, updated_at FROM operator WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOperatorForUpdate(ctx context.Context, id uuid.UUID) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperatorForUpdate, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.TotpConfirmedAt,
		&i.TotpLastStep,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO platform_audit_log (id, operator_id, action, target_type, target_id, tenant_id, before, after, reason, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11)
`

type InsertAuditParams struct {
	ID         uuid.UUID
	OperatorID *uuid.UUID
	Action     string
	TargetType string
	TargetID   *uuid.UUID
	TenantID   *uuid.UUID
	Before     []byte
	After      []byte
	Reason     string
	Ip         *netip.Addr
	UserAgent  *string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ID,
		arg.OperatorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TenantID,
		arg.Before,
		arg.After,
		arg.Reason,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const insertOperator = `-- name: InsertOperator :exec

INSERT INTO operator (id, email, password_hash, totp_secret_enc) VALUES ($1, $2, $3, $4)
`

type InsertOperatorParams struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  string
	TotpSecretEnc []byte
}

// All queries here run as orion_platform.
func (q *Queries) InsertOperator(ctx context.Context, arg InsertOperatorParams) error {
	_, err := q.db.Exec(ctx, insertOperator,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.TotpSecretEnc,
	)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO operator_recovery_code (id, operator_id, code_hash) VALUES ($1, $2, $3)
`

type InsertRecoveryCodeParams struct {
	ID         uuid.UUID
	OperatorID uuid.UUID
	CodeHash   []byte
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.ID, arg.OperatorID, arg.CodeHash)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, operator_id, action, target_type, target_id, tenant_id, before, after, reason, coalesce(host(ip), '')::text AS ip, user_agent, created_at
FROM platform_audit_log
WHERE id < $1
ORDER BY id DESC
LIMIT $2
`

type ListAuditParams struct {
	Before   uuid.UUID
	PageSize int32
}

type ListAuditRow struct {
	ID         uuid.UUID
	OperatorID *uuid.UUID
	Action     string
	TargetType string
	TargetID   *uuid.UUID
	TenantID   *uuid.UUID
	Before     []byte
	After      []byte
	Reason     string
	Ip         string
	UserAgent  *string
	CreatedAt  time.Time
}

// Newest first; the cursor is the id of the last row of the previous page.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit, arg.Before, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRow
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TenantID,
			&i.Before,
			&i.After,
			&i.Reason,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE operator_recovery_code SET used_at = $1
WHERE operator_id = $2 AND code_hash = $3 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	Now        *time.Time
	OperatorID uuid.UUID
	CodeHash   []byte
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.Now, arg.OperatorID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
