// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CashRoundingMode string

const (
	CashRoundingModeNearest CashRoundingMode = "nearest"
	CashRoundingModeDown    CashRoundingMode = "down"
	CashRoundingModeUp      CashRoundingMode = "up"
)

func (e *CashRoundingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashRoundingMode(s)
	case string:
		*e = CashRoundingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CashRoundingMode: %T", src)
	}
	return nil
}

type NullCashRoundingMode struct {
	CashRoundingMode CashRoundingMode
	Valid            bool // Valid is true if CashRoundingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashRoundingMode) Scan(value interface{}) error {
	if value == nil {
		ns.CashRoundingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashRoundingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashRoundingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashRoundingMode), nil
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusEarlyAccess SubscriptionStatus = "early_access"
	SubscriptionStatusTrialing    SubscriptionStatus = "trialing"
	SubscriptionStatusActive      SubscriptionStatus = "active"
	SubscriptionStatusPastDue     SubscriptionStatus = "past_due"
	SubscriptionStatusGrace       SubscriptionStatus = "grace"
	SubscriptionStatusReadOnly    SubscriptionStatus = "read_only"
	SubscriptionStatusCanceled    SubscriptionStatus = "canceled"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus
	Valid              bool // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type CashMovement struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	ShiftID      uuid.UUID
	Kind         string
	Amount       int64
	Reason       string
	StaffID      uuid.UUID
	DeviceTime   time.Time
	ReceivedAt   time.Time
	BusinessDate pgtype.Date
}

type Category struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	SortOrder  int32
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ChangeLog struct {
	TenantID   uuid.UUID
	Seq        int64
	EntityType string
	EntityID   uuid.UUID
	Op         string
	OutletID   *uuid.UUID
	CreatedAt  time.Time
}

type Device struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	OutletID         uuid.UUID
	DeviceCode       int32
	Name             string
	SecretHash       []byte
	PairedBy         uuid.UUID
	PairedAt         time.Time
	RevokedAt        *time.Time
	RevokedBy        *uuid.UUID
	LastSeenAt       *time.Time
	LastSyncAt       *time.Time
	AppVersion       *string
	ClockSkewMs      *int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UnsyncedEvents   int32
	OldestUnsyncedAt *time.Time
	HealthReportedAt *time.Time
}

type DeviceAlert struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	DeviceID   uuid.UUID
	Kind       string
	OpenedAt   time.Time
	Detail     []byte
	NotifiedAt *time.Time
	ResolvedAt *time.Time
}

type DeviceCodeCounter struct {
	OutletID uuid.UUID
	TenantID uuid.UUID
	NextCode int32
}

type EmailVerification struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type EntitlementKey struct {
	Key          string
	Kind         string
	Category     string
	Description  string
	Owner        string
	IsTemporary  bool
	DefaultValue int64
	CreatedAt    time.Time
}

type Flag struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	OutletID   uuid.UUID
	DeviceID   uuid.UUID
	EventID    uuid.UUID
	TargetType string
	TargetID   uuid.UUID
	Code       string
	Detail     []byte
	CreatedAt  time.Time
}

type Item struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	CategoryID *uuid.UUID
	Name       string
	Sku        *string
	Barcode    *string
	ImageUrl   *string
	TrackStock bool
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	StationID  *uuid.UUID
}

type ItemModifierGroup struct {
	TenantID  uuid.UUID
	ItemID    uuid.UUID
	GroupID   uuid.UUID
	SortOrder int32
}

type KitchenStation struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	SortOrder  int32
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Modifier struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	GroupID    uuid.UUID
	Name       string
	PriceDelta int64
	SortOrder  int32
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ModifierGroup struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	MinSelect  int32
	MaxSelect  int32
	Required   bool
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Operator struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	TotpSecretEnc   []byte
	TotpConfirmedAt *time.Time
	TotpLastStep    int64
	DisabledAt      *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type OperatorRecoveryCode struct {
	ID         uuid.UUID
	OperatorID uuid.UUID
	CodeHash   []byte
	UsedAt     *time.Time
	CreatedAt  time.Time
}

type Outlet struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	Code       string
	Address    string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type OutletSetting struct {
	OutletID             uuid.UUID
	TenantID             uuid.UUID
	Timezone             string
	BusinessDayCutoff    pgtype.Time
	PriceIncludesTax     bool
	TaxRateBp            int32
	ServiceChargeRateBp  int32
	ServiceChargeTaxable bool
	CashRoundingUnit     int32
	CashRoundingMode     CashRoundingMode
	ReceiptHeader        string
	ReceiptFooter        string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type OutletVariant struct {
	TenantID      uuid.UUID
	OutletID      uuid.UUID
	VariantID     uuid.UUID
	PriceOverride *int64
	Available     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Payment struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	SaleID    uuid.UUID
	Method    string
	Amount    int64
	Tendered  *int64
	Change    *int64
	Reference string
	Status    string
}

type Plan struct {
	ID        uuid.UUID
	Code      string
	Name      string
	IsPublic  bool
	CreatedAt time.Time
}

type PlanEntitlement struct {
	PlanID uuid.UUID
	Key    string
	Value  int64
}

type PlatformAuditLog struct {
	ID         uuid.UUID
	OperatorID *uuid.UUID
	Action     string
	TargetType string
	TargetID   *uuid.UUID
	TenantID   *uuid.UUID
	Before     []byte
	After      []byte
	Reason     string
	Ip         *netip.Addr
	UserAgent  *string
	CreatedAt  time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
	RevokedAt *time.Time
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  *time.Time
	CreatedAt    time.Time
	FinalizedAt  *time.Time
	ScheduledAt  time.Time
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	LeaderID  string
	Name      string
}

type RiverNotification struct {
	ID        int64
	CreatedAt time.Time
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  *time.Time
	UpdatedAt time.Time
}

type Role struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	IsSystem  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RolePermission struct {
	TenantID   uuid.UUID
	RoleID     uuid.UUID
	Permission string
}

type Sale struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	OutletID          uuid.UUID
	DeviceID          uuid.UUID
	ShiftID           uuid.UUID
	StaffID           uuid.UUID
	ReceiptNumber     string
	ReceiptDeviceCode int32
	ReceiptCounter    int64
	DeviceTime        time.Time
	ReceivedAt        time.Time
	BusinessDate      pgtype.Date
	PricingVersion    int32
	Pricing           []byte
	CatalogSeq        int64
	Subtotal          int64
	DiscountTotal     int64
	ServiceCharge     int64
	Tax               int64
	TaxIncluded       bool
	RoundingAmount    int64
	Total             int64
	Status            string
}

type SaleDiscount struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	SaleID     uuid.UUID
	SaleLineID *uuid.UUID
	Kind       string
	Value      int64
	Amount     int64
	Reason     string
	ApprovedBy *uuid.UUID
}

type SaleLine struct {
	ID                    uuid.UUID
	TenantID              uuid.UUID
	SaleID                uuid.UUID
	LineNo                int32
	VariantID             uuid.UUID
	NameSnapshot          string
	UnitPrice             int64
	Quantity              int32
	LineDiscount          int64
	AllocatedBillDiscount int64
	LineTotal             int64
}

type SaleLineModifier struct {
	TenantID     uuid.UUID
	SaleLineID   uuid.UUID
	Position     int32
	ModifierID   uuid.UUID
	NameSnapshot string
	PriceDelta   int64
}

type Shift struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	DeviceID     uuid.UUID
	OpenedBy     uuid.UUID
	OpenedAt     time.Time
	OpeningCash  int64
	BusinessDate pgtype.Date
	ReceivedAt   time.Time
	ClosedBy     *uuid.UUID
	ClosedAt     *time.Time
	CountedCash  *int64
	CloseEventID *uuid.UUID
}

type Staff struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	UserID       *uuid.UUID
	DisplayName  string
	PinHash      *string
	PinRotatedAt *time.Time
	Active       bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type StaffOutletRole struct {
	TenantID  uuid.UUID
	StaffID   uuid.UUID
	OutletID  uuid.UUID
	RoleID    uuid.UUID
	CreatedAt time.Time
}

type SyncInbox struct {
	TenantID       uuid.UUID
	DeviceID       uuid.UUID
	IdempotencyKey uuid.UUID
	ID             uuid.UUID
	OutletID       uuid.UUID
	StaffID        uuid.UUID
	EventType      string
	SchemaVersion  int32
	DeviceTime     time.Time
	PayloadHash    []byte
	Payload        []byte
	Status         string
	Code           *string
	Detail         *string
	DependsOn      *uuid.UUID
	ReceivedAt     time.Time
	AppliedAt      *time.Time
}

type Tenant struct {
	ID                 uuid.UUID
	Name               string
	Slug               string
	PlanID             uuid.UUID
	SubscriptionStatus SubscriptionStatus
	TrialEndsAt        *time.Time
	PaidUntil          *time.Time
	BillingStartsAt    *time.Time
	SuspendedAt        *time.Time
	ChangeSeq          int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type TenantAuditLog struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ActorType  string
	ActorID    *uuid.UUID
	Action     string
	TargetType string
	TargetID   *uuid.UUID
	Detail     []byte
	Ip         *netip.Addr
	CreatedAt  time.Time
}

type TenantEntitlementOverride struct {
	TenantID        uuid.UUID
	Key             string
	Value           int64
	Reason          string
	ExpiresAt       *time.Time
	SetByOperatorID *uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TenantMember struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	IsOwner   bool
	CreatedAt time.Time
}

type TermsAcceptance struct {
	TenantID   uuid.UUID
	UserID     uuid.UUID
	Version    string
	AcceptedAt time.Time
}

type UserAccount struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	Locale          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Variant struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ItemID     uuid.UUID
	Name       string
	Sku        *string
	Barcode    *string
	BasePrice  int64
	SortOrder  int32
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Void struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	SaleID       uuid.UUID
	ShiftID      uuid.UUID
	StaffID      uuid.UUID
	ApprovedBy   *uuid.UUID
	Reason       string
	DeviceTime   time.Time
	ReceivedAt   time.Time
	BusinessDate pgtype.Date
}
