// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CashRoundingMode string

const (
	CashRoundingModeNearest CashRoundingMode = "nearest"
	CashRoundingModeDown    CashRoundingMode = "down"
	CashRoundingModeUp      CashRoundingMode = "up"
)

func (e *CashRoundingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashRoundingMode(s)
	case string:
		*e = CashRoundingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CashRoundingMode: %T", src)
	}
	return nil
}

type NullCashRoundingMode struct {
	CashRoundingMode CashRoundingMode
	Valid            bool // Valid is true if CashRoundingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashRoundingMode) Scan(value interface{}) error {
	if value == nil {
		ns.CashRoundingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashRoundingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashRoundingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashRoundingMode), nil
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusEarlyAccess SubscriptionStatus = "early_access"
	SubscriptionStatusTrialing    SubscriptionStatus = "trialing"
	SubscriptionStatusActive      SubscriptionStatus = "active"
	SubscriptionStatusPastDue     SubscriptionStatus = "past_due"
	SubscriptionStatusGrace       SubscriptionStatus = "grace"
	SubscriptionStatusReadOnly    SubscriptionStatus = "read_only"
	SubscriptionStatusCanceled    SubscriptionStatus = "canceled"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus
	Valid              bool // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type ChangeLog struct {
	TenantID   uuid.UUID
	Seq        int64
	EntityType string
	EntityID   uuid.UUID
	Op         string
	OutletID   *uuid.UUID
	CreatedAt  time.Time
}

type EmailVerification struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Outlet struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	Code       string
	Address    string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type OutletSetting struct {
	OutletID             uuid.UUID
	TenantID             uuid.UUID
	Timezone             string
	BusinessDayCutoff    pgtype.Time
	PriceIncludesTax     bool
	TaxRateBp            int32
	ServiceChargeRateBp  int32
	ServiceChargeTaxable bool
	CashRoundingUnit     int32
	CashRoundingMode     CashRoundingMode
	ReceiptHeader        string
	ReceiptFooter        string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Plan struct {
	ID        uuid.UUID
	Code      string
	Name      string
	IsPublic  bool
	CreatedAt time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
	RevokedAt *time.Time
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  *time.Time
	CreatedAt    time.Time
	FinalizedAt  *time.Time
	ScheduledAt  time.Time
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	LeaderID  string
	Name      string
}

type RiverNotification struct {
	ID        int64
	CreatedAt time.Time
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  *time.Time
	UpdatedAt time.Time
}

type Tenant struct {
	ID                 uuid.UUID
	Name               string
	Slug               string
	PlanID             uuid.UUID
	SubscriptionStatus SubscriptionStatus
	TrialEndsAt        *time.Time
	PaidUntil          *time.Time
	BillingStartsAt    *time.Time
	SuspendedAt        *time.Time
	ChangeSeq          int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type TenantMember struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	IsOwner   bool
	CreatedAt time.Time
}

type UserAccount struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	Locale          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
