// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const allocateDeviceCode = `-- name: AllocateDeviceCode :one

INSERT INTO device_code_counter (outlet_id, tenant_id, next_code)
VALUES ($1, $2, 2)
ON CONFLICT (outlet_id) DO UPDATE SET next_code = device_code_counter.next_code + 1
RETURNING (next_code - 1)::integer AS code
`

type AllocateDeviceCodeParams struct {
	OutletID uuid.UUID
	TenantID uuid.UUID
}

// Devices.
// Hands out the next code for an outlet. The first call for an outlet inserts the counter; later
// calls take its row lock (after the tenant lock, in the fixed order) and increment it.
func (q *Queries) AllocateDeviceCode(ctx context.Context, arg AllocateDeviceCodeParams) (int32, error) {
	row := q.db.QueryRow(ctx, allocateDeviceCode, arg.OutletID, arg.TenantID)
	var code int32
	err := row.Scan(&code)
	return code, err
}

const countActiveDevices = `-- name: CountActiveDevices :one
SELECT count(*) FROM device WHERE tenant_id = $1 AND revoked_at IS NULL
`

func (q *Queries) CountActiveDevices(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDevices, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveStaff = `-- name: CountActiveStaff :one
SELECT count(*) FROM staff WHERE tenant_id = $1 AND active
`

func (q *Queries) CountActiveStaff(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveStaff, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStaffOutletRoles = `-- name: DeleteStaffOutletRoles :exec
DELETE FROM staff_outlet_role
WHERE tenant_id = $1 AND staff_id = $2
  AND (outlet_id, role_id) IN (
      SELECT o.id, r.id
      FROM unnest($3::uuid[]) WITH ORDINALITY AS o(id, n)
      JOIN unnest($4::uuid[]) WITH ORDINALITY AS r(id, n) ON r.n = o.n
  )
`

type DeleteStaffOutletRolesParams struct {
	TenantID  uuid.UUID
	StaffID   uuid.UUID
	OutletIds []uuid.UUID
	RoleIds   []uuid.UUID
}

func (q *Queries) DeleteStaffOutletRoles(ctx context.Context, arg DeleteStaffOutletRolesParams) error {
	_, err := q.db.Exec(ctx, deleteStaffOutletRoles,
		arg.TenantID,
		arg.StaffID,
		arg.OutletIds,
		arg.RoleIds,
	)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, tenant_id, outlet_id, device_code, name, secret_hash, paired_by, paired_at, revoked_at, revoked_by, last_seen_at, last_sync_at, app_version, clock_skew_ms, created_at, updated_at FROM device WHERE tenant_id = $1 AND id = $2
`

type GetDeviceParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.TenantID, arg.ID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.DeviceCode,
		&i.Name,
		&i.SecretHash,
		&i.PairedBy,
		&i.PairedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.LastSeenAt,
		&i.LastSyncAt,
		&i.AppVersion,
		&i.ClockSkewMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceForShare = `-- name: GetDeviceForShare :one

SELECT id, tenant_id, outlet_id, device_code, name, secret_hash, paired_by, paired_at, revoked_at, revoked_by, last_seen_at, last_sync_at, app_version, clock_skew_ms, created_at, updated_at FROM device WHERE tenant_id = $1 AND id = $2 FOR SHARE
`

type GetDeviceForShareParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// Used while projecting synced events (internal/sync). They run inside the event's transaction.
// Holding a share lock on the device until the event commits makes revocation (an UPDATE) wait for
// events in flight, so nothing commits after a revoke has returned.
func (q *Queries) GetDeviceForShare(ctx context.Context, arg GetDeviceForShareParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceForShare, arg.TenantID, arg.ID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.DeviceCode,
		&i.Name,
		&i.SecretHash,
		&i.PairedBy,
		&i.PairedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.LastSeenAt,
		&i.LastSyncAt,
		&i.AppVersion,
		&i.ClockSkewMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceForUpdate = `-- name: GetDeviceForUpdate :one
SELECT id, tenant_id, outlet_id, device_code, name, secret_hash, paired_by, paired_at, revoked_at, revoked_by, last_seen_at, last_sync_at, app_version, clock_skew_ms, created_at, updated_at FROM device WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetDeviceForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetDeviceForUpdate(ctx context.Context, arg GetDeviceForUpdateParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceForUpdate, arg.TenantID, arg.ID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.DeviceCode,
		&i.Name,
		&i.SecretHash,
		&i.PairedBy,
		&i.PairedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.LastSeenAt,
		&i.LastSyncAt,
		&i.AppVersion,
		&i.ClockSkewMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT is_owner FROM tenant_member WHERE tenant_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, getMember, arg.TenantID, arg.UserID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const getMemberAccess = `-- name: GetMemberAccess :many
SELECT m.is_owner, sor.outlet_id, rp.permission
FROM tenant_member m
LEFT JOIN staff s ON s.tenant_id = m.tenant_id AND s.user_id = m.user_id AND s.active
LEFT JOIN staff_outlet_role sor ON sor.tenant_id = s.tenant_id AND sor.staff_id = s.id
LEFT JOIN role_permission rp ON rp.tenant_id = sor.tenant_id AND rp.role_id = sor.role_id
WHERE m.tenant_id = $1 AND m.user_id = $2
`

type GetMemberAccessParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type GetMemberAccessRow struct {
	IsOwner    bool
	OutletID   *uuid.UUID
	Permission *string
}

// One member's role permissions per outlet, in one query. Zero rows means the user is not a
// member. Inactive staff hold no roles.
func (q *Queries) GetMemberAccess(ctx context.Context, arg GetMemberAccessParams) ([]GetMemberAccessRow, error) {
	rows, err := q.db.Query(ctx, getMemberAccess, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemberAccessRow
	for rows.Next() {
		var i GetMemberAccessRow
		if err := rows.Scan(&i.IsOwner, &i.OutletID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, tenant_id, user_id, family_id, token_hash, created_at, expires_at, used_at, revoked_at FROM refresh_token WHERE tenant_id = $1 AND token_hash = $2 FOR UPDATE
`

type GetRefreshTokenForUpdateParams struct {
	TenantID  uuid.UUID
	TokenHash []byte
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, arg GetRefreshTokenForUpdateParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, arg.TenantID, arg.TokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getStaff = `-- name: GetStaff :one
SELECT s.id, s.user_id, s.display_name, s.pin_hash, s.pin_rotated_at, s.active, s.created_at,
       coalesce(m.is_owner, false)::boolean AS is_owner
FROM staff s
LEFT JOIN tenant_member m ON m.tenant_id = s.tenant_id AND m.user_id = s.user_id
WHERE s.tenant_id = $1 AND s.id = $2
`

type GetStaffParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetStaffRow struct {
	ID           uuid.UUID
	UserID       *uuid.UUID
	DisplayName  string
	PinHash      *string
	PinRotatedAt *time.Time
	Active       bool
	CreatedAt    time.Time
	IsOwner      bool
}

func (q *Queries) GetStaff(ctx context.Context, arg GetStaffParams) (GetStaffRow, error) {
	row := q.db.QueryRow(ctx, getStaff, arg.TenantID, arg.ID)
	var i GetStaffRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.PinHash,
		&i.PinRotatedAt,
		&i.Active,
		&i.CreatedAt,
		&i.IsOwner,
	)
	return i, err
}

const getStaffForUpdate = `-- name: GetStaffForUpdate :one
SELECT s.id, s.user_id, s.display_name, s.pin_hash, s.pin_rotated_at, s.active, s.created_at,
       coalesce(m.is_owner, false)::boolean AS is_owner
FROM staff s
LEFT JOIN tenant_member m ON m.tenant_id = s.tenant_id AND m.user_id = s.user_id
WHERE s.tenant_id = $1 AND s.id = $2
FOR UPDATE OF s
`

type GetStaffForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetStaffForUpdateRow struct {
	ID           uuid.UUID
	UserID       *uuid.UUID
	DisplayName  string
	PinHash      *string
	PinRotatedAt *time.Time
	Active       bool
	CreatedAt    time.Time
	IsOwner      bool
}

func (q *Queries) GetStaffForUpdate(ctx context.Context, arg GetStaffForUpdateParams) (GetStaffForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getStaffForUpdate, arg.TenantID, arg.ID)
	var i GetStaffForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.PinHash,
		&i.PinRotatedAt,
		&i.Active,
		&i.CreatedAt,
		&i.IsOwner,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, email_verified_at, locale, created_at FROM user_account WHERE id = $1
`

type GetUserRow struct {
	ID              uuid.UUID
	Email           string
	EmailVerifiedAt *time.Time
	Locale          string
	CreatedAt       time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForEmail = `-- name: GetUserForEmail :one
SELECT id, email, email_verified_at, locale FROM user_account WHERE id = $1
`

type GetUserForEmailRow struct {
	ID              uuid.UUID
	Email           string
	EmailVerifiedAt *time.Time
	Locale          string
}

func (q *Queries) GetUserForEmail(ctx context.Context, id uuid.UUID) (GetUserForEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserForEmail, id)
	var i GetUserForEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Locale,
	)
	return i, err
}

const getVerificationForUpdate = `-- name: GetVerificationForUpdate :one
SELECT id, tenant_id, user_id, token_hash, created_at, expires_at, used_at FROM email_verification WHERE tenant_id = $1 AND token_hash = $2 FOR UPDATE
`

type GetVerificationForUpdateParams struct {
	TenantID  uuid.UUID
	TokenHash []byte
}

func (q *Queries) GetVerificationForUpdate(ctx context.Context, arg GetVerificationForUpdateParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getVerificationForUpdate, arg.TenantID, arg.TokenHash)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO device (id, tenant_id, outlet_id, device_code, name, secret_hash, paired_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertDeviceParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	OutletID   uuid.UUID
	DeviceCode int32
	Name       string
	SecretHash []byte
	PairedBy   uuid.UUID
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.Exec(ctx, insertDevice,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.DeviceCode,
		arg.Name,
		arg.SecretHash,
		arg.PairedBy,
	)
	return err
}

const insertEmailVerification = `-- name: InsertEmailVerification :exec

INSERT INTO email_verification (id, tenant_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEmailVerificationParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

// Queries below run as orion_platform, from the worker.
func (q *Queries) InsertEmailVerification(ctx context.Context, arg InsertEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, insertEmailVerification,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO tenant_member (tenant_id, user_id, is_owner)
VALUES ($1, $2, $3)
`

type InsertMemberParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	IsOwner  bool
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember, arg.TenantID, arg.UserID, arg.IsOwner)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_token (id, tenant_id, user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRefreshTokenParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertRole = `-- name: InsertRole :exec
INSERT INTO role (id, tenant_id, name, is_system) VALUES ($1, $2, $3, $4)
`

type InsertRoleParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	IsSystem bool
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) error {
	_, err := q.db.Exec(ctx, insertRole,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.IsSystem,
	)
	return err
}

const insertRolePermissions = `-- name: InsertRolePermissions :exec
INSERT INTO role_permission (tenant_id, role_id, permission)
SELECT $1::uuid, $2::uuid, unnest($3::text[])
`

type InsertRolePermissionsParams struct {
	TenantID    uuid.UUID
	RoleID      uuid.UUID
	Permissions []string
}

// COPY is not allowed into tables with row-level security, so bulk inserts unnest an array.
func (q *Queries) InsertRolePermissions(ctx context.Context, arg InsertRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, insertRolePermissions, arg.TenantID, arg.RoleID, arg.Permissions)
	return err
}

const insertStaff = `-- name: InsertStaff :exec
INSERT INTO staff (id, tenant_id, user_id, display_name, pin_hash, pin_rotated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertStaffParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	UserID       *uuid.UUID
	DisplayName  string
	PinHash      *string
	PinRotatedAt *time.Time
}

func (q *Queries) InsertStaff(ctx context.Context, arg InsertStaffParams) error {
	_, err := q.db.Exec(ctx, insertStaff,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.DisplayName,
		arg.PinHash,
		arg.PinRotatedAt,
	)
	return err
}

const insertStaffOutletRoles = `-- name: InsertStaffOutletRoles :exec
INSERT INTO staff_outlet_role (tenant_id, staff_id, outlet_id, role_id)
SELECT $1::uuid, $2::uuid, o.id, r.id
FROM unnest($3::uuid[]) WITH ORDINALITY AS o(id, n)
JOIN unnest($4::uuid[]) WITH ORDINALITY AS r(id, n) ON r.n = o.n
ON CONFLICT DO NOTHING
`

type InsertStaffOutletRolesParams struct {
	TenantID  uuid.UUID
	StaffID   uuid.UUID
	OutletIds []uuid.UUID
	RoleIds   []uuid.UUID
}

func (q *Queries) InsertStaffOutletRoles(ctx context.Context, arg InsertStaffOutletRolesParams) error {
	_, err := q.db.Exec(ctx, insertStaffOutletRoles,
		arg.TenantID,
		arg.StaffID,
		arg.OutletIds,
		arg.RoleIds,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO user_account (id, email, password_hash, email_verified_at, locale)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserParams struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	Locale          string
}

// No RETURNING: orion_app may insert a user but only read members of its own tenant, and this
// user is not a member yet. The caller generates the id.
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.Locale,
	)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT id, tenant_id, outlet_id, device_code, name, secret_hash, paired_by, paired_at, revoked_at, revoked_by, last_seen_at, last_sync_at, app_version, clock_skew_ms, created_at, updated_at FROM device
WHERE tenant_id = $1 AND id > $2
  AND ($3::boolean OR outlet_id = ANY($4::uuid[]))
ORDER BY id
LIMIT $5
`

type ListDevicesParams struct {
	TenantID   uuid.UUID
	After      uuid.UUID
	AllOutlets bool
	OutletIds  []uuid.UUID
	PageSize   int32
}

// Non-owners see only the outlets where they may manage devices.
func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.TenantID,
		arg.After,
		arg.AllOutlets,
		arg.OutletIds,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OutletID,
			&i.DeviceCode,
			&i.Name,
			&i.SecretHash,
			&i.PairedBy,
			&i.PairedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.LastSeenAt,
			&i.LastSyncAt,
			&i.AppVersion,
			&i.ClockSkewMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsOfStaffAt = `-- name: ListPermissionsOfStaffAt :many
SELECT sor.staff_id, rp.permission
FROM staff_outlet_role sor
JOIN role_permission rp ON rp.tenant_id = sor.tenant_id AND rp.role_id = sor.role_id
WHERE sor.tenant_id = $1 AND sor.outlet_id = $2 AND sor.staff_id = ANY($3::uuid[])
ORDER BY sor.staff_id, rp.permission
`

type ListPermissionsOfStaffAtParams struct {
	TenantID uuid.UUID
	OutletID uuid.UUID
	StaffIds []uuid.UUID
}

type ListPermissionsOfStaffAtRow struct {
	StaffID    uuid.UUID
	Permission string
}

func (q *Queries) ListPermissionsOfStaffAt(ctx context.Context, arg ListPermissionsOfStaffAtParams) ([]ListPermissionsOfStaffAtRow, error) {
	rows, err := q.db.Query(ctx, listPermissionsOfStaffAt, arg.TenantID, arg.OutletID, arg.StaffIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsOfStaffAtRow
	for rows.Next() {
		var i ListPermissionsOfStaffAtRow
		if err := rows.Scan(&i.StaffID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT role_id, permission FROM role_permission
WHERE tenant_id = $1 AND role_id = ANY($2::uuid[])
ORDER BY role_id, permission
`

type ListRolePermissionsParams struct {
	TenantID uuid.UUID
	RoleIds  []uuid.UUID
}

type ListRolePermissionsRow struct {
	RoleID     uuid.UUID
	Permission string
}

// Permissions for many roles at once, assembled in Go: two queries however many roles there are.
func (q *Queries) ListRolePermissions(ctx context.Context, arg ListRolePermissionsParams) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, arg.TenantID, arg.RoleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolePermissionsRow
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(&i.RoleID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, tenant_id, name, is_system, created_at, updated_at FROM role WHERE tenant_id = $1 ORDER BY is_system DESC, name
`

func (q *Queries) ListRoles(ctx context.Context, tenantID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByIDs = `-- name: ListRolesByIDs :many
SELECT id, tenant_id, name, is_system, created_at, updated_at FROM role WHERE tenant_id = $1 AND id = ANY($2::uuid[])
`

type ListRolesByIDsParams struct {
	TenantID uuid.UUID
	RoleIds  []uuid.UUID
}

func (q *Queries) ListRolesByIDs(ctx context.Context, arg ListRolesByIDsParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByIDs, arg.TenantID, arg.RoleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterCandidates = `-- name: ListRosterCandidates :many

SELECT s.id, s.display_name, s.pin_hash, coalesce(m.is_owner, false)::boolean AS is_owner,
       (s.active AND (coalesce(m.is_owner, false) OR EXISTS (
            SELECT 1 FROM staff_outlet_role sor
            WHERE sor.tenant_id = s.tenant_id AND sor.staff_id = s.id AND sor.outlet_id = $1)))::boolean AS on_roster
FROM staff s
LEFT JOIN tenant_member m ON m.tenant_id = s.tenant_id AND m.user_id = s.user_id
WHERE s.tenant_id = $2 AND s.id = ANY($3::uuid[])
ORDER BY s.display_name, s.id
`

type ListRosterCandidatesParams struct {
	OutletID uuid.UUID
	TenantID uuid.UUID
	StaffIds []uuid.UUID
}

type ListRosterCandidatesRow struct {
	ID          uuid.UUID
	DisplayName string
	PinHash     *string
	IsOwner     bool
	OnRoster    bool
}

// The POS pull: roster entries for the staff whose records changed.
// For each staff id: whether the person belongs on this outlet's roster (active, and an owner or
// assigned to the outlet). Those who do not are reported as removed.
func (q *Queries) ListRosterCandidates(ctx context.Context, arg ListRosterCandidatesParams) ([]ListRosterCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listRosterCandidates, arg.OutletID, arg.TenantID, arg.StaffIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosterCandidatesRow
	for rows.Next() {
		var i ListRosterCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.PinHash,
			&i.IsOwner,
			&i.OnRoster,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterPermissions = `-- name: ListRosterPermissions :many
SELECT sor.staff_id, rp.permission
FROM staff_outlet_role sor
JOIN role_permission rp ON rp.tenant_id = sor.tenant_id AND rp.role_id = sor.role_id
WHERE sor.tenant_id = $1 AND sor.outlet_id = $2
ORDER BY sor.staff_id, rp.permission
`

type ListRosterPermissionsParams struct {
	TenantID uuid.UUID
	OutletID uuid.UUID
}

type ListRosterPermissionsRow struct {
	StaffID    uuid.UUID
	Permission string
}

// Everyone's permissions at the outlet in one query.
func (q *Queries) ListRosterPermissions(ctx context.Context, arg ListRosterPermissionsParams) ([]ListRosterPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRosterPermissions, arg.TenantID, arg.OutletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosterPermissionsRow
	for rows.Next() {
		var i ListRosterPermissionsRow
		if err := rows.Scan(&i.StaffID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterStaff = `-- name: ListRosterStaff :many
SELECT s.id, s.display_name, s.pin_hash, coalesce(m.is_owner, false)::boolean AS is_owner
FROM staff s
LEFT JOIN tenant_member m ON m.tenant_id = s.tenant_id AND m.user_id = s.user_id
WHERE s.tenant_id = $1 AND s.active
  AND (coalesce(m.is_owner, false) OR EXISTS (
        SELECT 1 FROM staff_outlet_role sor
        WHERE sor.tenant_id = s.tenant_id AND sor.staff_id = s.id AND sor.outlet_id = $2))
ORDER BY s.display_name, s.id
`

type ListRosterStaffParams struct {
	TenantID uuid.UUID
	OutletID uuid.UUID
}

type ListRosterStaffRow struct {
	ID          uuid.UUID
	DisplayName string
	PinHash     *string
	IsOwner     bool
}

// The staff a device at this outlet shows on its lock screen: active staff assigned to the outlet,
// and owners (who may act anywhere).
func (q *Queries) ListRosterStaff(ctx context.Context, arg ListRosterStaffParams) ([]ListRosterStaffRow, error) {
	rows, err := q.db.Query(ctx, listRosterStaff, arg.TenantID, arg.OutletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosterStaffRow
	for rows.Next() {
		var i ListRosterStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.PinHash,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaff = `-- name: ListStaff :many
SELECT s.id, s.user_id, s.display_name, s.pin_hash, s.pin_rotated_at, s.active, s.created_at,
       coalesce(m.is_owner, false)::boolean AS is_owner
FROM staff s
LEFT JOIN tenant_member m ON m.tenant_id = s.tenant_id AND m.user_id = s.user_id
WHERE s.tenant_id = $1 AND s.id > $2
ORDER BY s.id
LIMIT $3
`

type ListStaffParams struct {
	TenantID uuid.UUID
	After    uuid.UUID
	PageSize int32
}

type ListStaffRow struct {
	ID           uuid.UUID
	UserID       *uuid.UUID
	DisplayName  string
	PinHash      *string
	PinRotatedAt *time.Time
	Active       bool
	CreatedAt    time.Time
	IsOwner      bool
}

func (q *Queries) ListStaff(ctx context.Context, arg ListStaffParams) ([]ListStaffRow, error) {
	rows, err := q.db.Query(ctx, listStaff, arg.TenantID, arg.After, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffRow
	for rows.Next() {
		var i ListStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.PinHash,
			&i.PinRotatedAt,
			&i.Active,
			&i.CreatedAt,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffOutletRoles = `-- name: ListStaffOutletRoles :many
SELECT staff_id, outlet_id, role_id FROM staff_outlet_role
WHERE tenant_id = $1 AND staff_id = ANY($2::uuid[])
ORDER BY staff_id, outlet_id, role_id
`

type ListStaffOutletRolesParams struct {
	TenantID uuid.UUID
	StaffIds []uuid.UUID
}

type ListStaffOutletRolesRow struct {
	StaffID  uuid.UUID
	OutletID uuid.UUID
	RoleID   uuid.UUID
}

// The outlet roles of a page of staff, in one query.
func (q *Queries) ListStaffOutletRoles(ctx context.Context, arg ListStaffOutletRolesParams) ([]ListStaffOutletRolesRow, error) {
	rows, err := q.db.Query(ctx, listStaffOutletRoles, arg.TenantID, arg.StaffIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffOutletRolesRow
	for rows.Next() {
		var i ListStaffOutletRolesRow
		if err := rows.Scan(&i.StaffID, &i.OutletID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffPermissionsAt = `-- name: ListStaffPermissionsAt :many
SELECT rp.permission
FROM staff_outlet_role sor
JOIN role_permission rp ON rp.tenant_id = sor.tenant_id AND rp.role_id = sor.role_id
WHERE sor.tenant_id = $1 AND sor.staff_id = $2 AND sor.outlet_id = $3
ORDER BY rp.permission
`

type ListStaffPermissionsAtParams struct {
	TenantID uuid.UUID
	StaffID  uuid.UUID
	OutletID uuid.UUID
}

// What one staff member may do at an outlet.
func (q *Queries) ListStaffPermissionsAt(ctx context.Context, arg ListStaffPermissionsAtParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaffPermissionsAt, arg.TenantID, arg.StaffID, arg.OutletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE user_account SET email_verified_at = $1 WHERE id = $2 AND email_verified_at IS NULL
`

type MarkEmailVerifiedParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markEmailVerified, arg.Now, arg.ID)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_token SET used_at = $1 WHERE id = $2
`

type MarkRefreshTokenUsedParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.Now, arg.ID)
	return err
}

const markVerificationUsed = `-- name: MarkVerificationUsed :exec
UPDATE email_verification SET used_at = $1 WHERE id = $2
`

type MarkVerificationUsedParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkVerificationUsed(ctx context.Context, arg MarkVerificationUsedParams) error {
	_, err := q.db.Exec(ctx, markVerificationUsed, arg.Now, arg.ID)
	return err
}

const purgeEmailVerifications = `-- name: PurgeEmailVerifications :execrows
DELETE FROM email_verification WHERE expires_at < $1
`

func (q *Queries) PurgeEmailVerifications(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEmailVerifications, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeRefreshTokens = `-- name: PurgeRefreshTokens :execrows
DELETE FROM refresh_token WHERE expires_at < $1
`

func (q *Queries) PurgeRefreshTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeRefreshTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDeviceContact = `-- name: RecordDeviceContact :exec
UPDATE device SET last_seen_at = $1, app_version = $2, clock_skew_ms = $3
WHERE tenant_id = $4 AND id = $5
`

type RecordDeviceContactParams struct {
	Now         *time.Time
	AppVersion  *string
	ClockSkewMs *int32
	TenantID    uuid.UUID
	ID          uuid.UUID
}

// Stamps a token exchange: when the device was seen, its app version and how far its clock is off.
func (q *Queries) RecordDeviceContact(ctx context.Context, arg RecordDeviceContactParams) error {
	_, err := q.db.Exec(ctx, recordDeviceContact,
		arg.Now,
		arg.AppVersion,
		arg.ClockSkewMs,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const recordDeviceSync = `-- name: RecordDeviceSync :exec
UPDATE device
SET last_sync_at = $1, last_seen_at = $1,
    app_version = coalesce($2, app_version),
    clock_skew_ms = coalesce($3, clock_skew_ms)
WHERE tenant_id = $4 AND id = $5
`

type RecordDeviceSyncParams struct {
	Now         *time.Time
	AppVersion  *string
	ClockSkewMs *int32
	TenantID    uuid.UUID
	ID          uuid.UUID
}

// Stamps a push: when the device last synced, its app version and how far its clock is off.
func (q *Queries) RecordDeviceSync(ctx context.Context, arg RecordDeviceSyncParams) error {
	_, err := q.db.Exec(ctx, recordDeviceSync,
		arg.Now,
		arg.AppVersion,
		arg.ClockSkewMs,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const revokeDevice = `-- name: RevokeDevice :exec
UPDATE device SET revoked_at = $1, revoked_by = $2
WHERE tenant_id = $3 AND id = $4 AND revoked_at IS NULL
`

type RevokeDeviceParams struct {
	Now       *time.Time
	RevokedBy *uuid.UUID
	TenantID  uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeDevice,
		arg.Now,
		arg.RevokedBy,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_token SET revoked_at = $1
WHERE id IN (
    SELECT t.id FROM refresh_token t
    WHERE t.tenant_id = $2 AND t.family_id = $3 AND t.revoked_at IS NULL
    ORDER BY t.id
    FOR UPDATE
)
`

type RevokeRefreshFamilyParams struct {
	Now      *time.Time
	TenantID uuid.UUID
	FamilyID uuid.UUID
}

// Rows are locked in id order so two concurrent revocations of one family cannot deadlock.
func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, arg.Now, arg.TenantID, arg.FamilyID)
	return err
}

const setStaffPIN = `-- name: SetStaffPIN :exec
UPDATE staff SET pin_hash = $1, pin_rotated_at = $2
WHERE tenant_id = $3 AND id = $4
`

type SetStaffPINParams struct {
	PinHash  *string
	Now      *time.Time
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) SetStaffPIN(ctx context.Context, arg SetStaffPINParams) error {
	_, err := q.db.Exec(ctx, setStaffPIN,
		arg.PinHash,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE device SET last_seen_at = $1
WHERE tenant_id = $2 AND id = $3 AND (last_seen_at IS NULL OR last_seen_at < $4)
`

type TouchDeviceParams struct {
	Now         *time.Time
	TenantID    uuid.UUID
	ID          uuid.UUID
	StaleBefore *time.Time
}

// Keeps last_seen_at fresh without a write on every request: the caller passes a stale_before a
// minute in the past, so a device seen more recently than that is left alone.
func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.Exec(ctx, touchDevice,
		arg.Now,
		arg.TenantID,
		arg.ID,
		arg.StaleBefore,
	)
	return err
}

const updateStaff = `-- name: UpdateStaff :exec
UPDATE staff SET display_name = $1, active = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateStaffParams struct {
	DisplayName string
	Active      bool
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) error {
	_, err := q.db.Exec(ctx, updateStaff,
		arg.DisplayName,
		arg.Active,
		arg.TenantID,
		arg.ID,
	)
	return err
}
