// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMember = `-- name: GetMember :one
SELECT is_owner FROM tenant_member WHERE tenant_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, getMember, arg.TenantID, arg.UserID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, tenant_id, user_id, family_id, token_hash, created_at, expires_at, used_at, revoked_at FROM refresh_token WHERE tenant_id = $1 AND token_hash = $2 FOR UPDATE
`

type GetRefreshTokenForUpdateParams struct {
	TenantID  uuid.UUID
	TokenHash []byte
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, arg GetRefreshTokenForUpdateParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, arg.TenantID, arg.TokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, email_verified_at, locale, created_at FROM user_account WHERE id = $1
`

type GetUserRow struct {
	ID              uuid.UUID
	Email           string
	EmailVerifiedAt *time.Time
	Locale          string
	CreatedAt       time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}

const getUserForEmail = `-- name: GetUserForEmail :one
SELECT id, email, email_verified_at, locale FROM user_account WHERE id = $1
`

type GetUserForEmailRow struct {
	ID              uuid.UUID
	Email           string
	EmailVerifiedAt *time.Time
	Locale          string
}

func (q *Queries) GetUserForEmail(ctx context.Context, id uuid.UUID) (GetUserForEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserForEmail, id)
	var i GetUserForEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Locale,
	)
	return i, err
}

const getVerificationForUpdate = `-- name: GetVerificationForUpdate :one
SELECT id, tenant_id, user_id, token_hash, created_at, expires_at, used_at FROM email_verification WHERE tenant_id = $1 AND token_hash = $2 FOR UPDATE
`

type GetVerificationForUpdateParams struct {
	TenantID  uuid.UUID
	TokenHash []byte
}

func (q *Queries) GetVerificationForUpdate(ctx context.Context, arg GetVerificationForUpdateParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getVerificationForUpdate, arg.TenantID, arg.TokenHash)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const insertEmailVerification = `-- name: InsertEmailVerification :exec

INSERT INTO email_verification (id, tenant_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEmailVerificationParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

// Queries below run as orion_platform, from the worker.
func (q *Queries) InsertEmailVerification(ctx context.Context, arg InsertEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, insertEmailVerification,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO tenant_member (tenant_id, user_id, is_owner)
VALUES ($1, $2, $3)
`

type InsertMemberParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	IsOwner  bool
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember, arg.TenantID, arg.UserID, arg.IsOwner)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_token (id, tenant_id, user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRefreshTokenParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO user_account (id, email, password_hash, email_verified_at, locale)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserParams struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	Locale          string
}

// No RETURNING: orion_app may insert a user but only read members of its own tenant, and this
// user is not a member yet. The caller generates the id.
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.Locale,
	)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE user_account SET email_verified_at = $1 WHERE id = $2 AND email_verified_at IS NULL
`

type MarkEmailVerifiedParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markEmailVerified, arg.Now, arg.ID)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_token SET used_at = $1 WHERE id = $2
`

type MarkRefreshTokenUsedParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.Now, arg.ID)
	return err
}

const markVerificationUsed = `-- name: MarkVerificationUsed :exec
UPDATE email_verification SET used_at = $1 WHERE id = $2
`

type MarkVerificationUsedParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkVerificationUsed(ctx context.Context, arg MarkVerificationUsedParams) error {
	_, err := q.db.Exec(ctx, markVerificationUsed, arg.Now, arg.ID)
	return err
}

const purgeEmailVerifications = `-- name: PurgeEmailVerifications :execrows
DELETE FROM email_verification WHERE expires_at < $1
`

func (q *Queries) PurgeEmailVerifications(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEmailVerifications, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeRefreshTokens = `-- name: PurgeRefreshTokens :execrows
DELETE FROM refresh_token WHERE expires_at < $1
`

func (q *Queries) PurgeRefreshTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeRefreshTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_token SET revoked_at = $1
WHERE id IN (
    SELECT t.id FROM refresh_token t
    WHERE t.tenant_id = $2 AND t.family_id = $3 AND t.revoked_at IS NULL
    ORDER BY t.id
    FOR UPDATE
)
`

type RevokeRefreshFamilyParams struct {
	Now      *time.Time
	TenantID uuid.UUID
	FamilyID uuid.UUID
}

// Rows are locked in id order so two concurrent revocations of one family cannot deadlock.
func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, arg.Now, arg.TenantID, arg.FamilyID)
	return err
}
