-- Users, tenant membership, refresh tokens and email verification (BACKEND_PLAN.md sections 4.3
-- and 6.1).
--
-- user_account is global: a person exists before any tenant does, and may belong to several. It
-- therefore has no tenant_id, but it is still isolated: orion_app sees a user only while it is a
-- member of the current tenant, and it cannot read password_hash at all. The one place that must
-- find a user before a tenant is known, login, goes through auth_find_user() below.

-- +goose Up
CREATE TABLE user_account (
    id                uuid PRIMARY KEY,
    -- Stored lowercase and trimmed so UNIQUE means what people expect, without the citext extension.
    email             text NOT NULL UNIQUE
        CHECK (email = lower(btrim(email)) AND length(email) <= 254 AND email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
    password_hash     text NOT NULL,
    email_verified_at timestamptz,
    locale            text NOT NULL DEFAULT 'id-ID' CHECK (locale IN ('id-ID', 'en')),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tenant_member (
    tenant_id  uuid NOT NULL REFERENCES tenant (id),
    user_id    uuid NOT NULL REFERENCES user_account (id),
    is_owner   boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, user_id)
);

-- Login lists a user's tenants by user_id, and the primary key starts with tenant_id.
CREATE INDEX tenant_member_user_id_idx ON tenant_member (user_id);

-- A refresh token is single use. Using it again, whether it was rotated or revoked, is treated as
-- theft: the whole family (every token descended from one login) is revoked. The token string
-- carries the tenant id, so lookups run inside that tenant's row-level security.
CREATE TABLE refresh_token (
    id         uuid PRIMARY KEY,
    tenant_id  uuid NOT NULL REFERENCES tenant (id),
    user_id    uuid NOT NULL REFERENCES user_account (id),
    family_id  uuid NOT NULL,
    token_hash bytea NOT NULL CHECK (octet_length(token_hash) = 32),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    used_at    timestamptz,
    revoked_at timestamptz,
    UNIQUE (tenant_id, token_hash)
);

-- Reuse detection and logout revoke a family.
CREATE INDEX refresh_token_family_idx ON refresh_token (tenant_id, family_id);

CREATE TABLE email_verification (
    id         uuid PRIMARY KEY,
    tenant_id  uuid NOT NULL REFERENCES tenant (id),
    user_id    uuid NOT NULL REFERENCES user_account (id),
    token_hash bytea NOT NULL CHECK (octet_length(token_hash) = 32),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    used_at    timestamptz,
    UNIQUE (tenant_id, token_hash)
);

CREATE TRIGGER user_account_set_updated_at BEFORE UPDATE ON user_account
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Row-level security.
ALTER TABLE user_account ENABLE ROW LEVEL SECURITY;
CREATE POLICY member_select ON user_account FOR SELECT TO orion_app
    USING (EXISTS (SELECT 1 FROM tenant_member m
                   WHERE m.user_id = user_account.id AND m.tenant_id = current_tenant_id()));
CREATE POLICY member_update ON user_account FOR UPDATE TO orion_app
    USING (EXISTS (SELECT 1 FROM tenant_member m
                   WHERE m.user_id = user_account.id AND m.tenant_id = current_tenant_id()))
    WITH CHECK (EXISTS (SELECT 1 FROM tenant_member m
                        WHERE m.user_id = user_account.id AND m.tenant_id = current_tenant_id()));
-- A user is created before it is a member, so insert cannot be limited to members. Inserting
-- without RETURNING (ids are generated by the caller) never needs to read the row back.
CREATE POLICY any_insert ON user_account FOR INSERT TO orion_app WITH CHECK (true);
CREATE POLICY platform_all ON user_account TO orion_platform USING (true) WITH CHECK (true);

ALTER TABLE tenant_member ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON tenant_member TO orion_app
    USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY platform_all ON tenant_member TO orion_platform USING (true) WITH CHECK (true);

ALTER TABLE refresh_token ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON refresh_token TO orion_app
    USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY platform_all ON refresh_token TO orion_platform USING (true) WITH CHECK (true);

ALTER TABLE email_verification ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON email_verification TO orion_app
    USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY platform_all ON email_verification TO orion_platform USING (true) WITH CHECK (true);

-- Grants. The app role never reads password_hash: login gets it through auth_find_user().
GRANT SELECT (id, email, email_verified_at, locale, created_at, updated_at) ON user_account TO orion_app;
GRANT INSERT (id, email, password_hash, email_verified_at, locale) ON user_account TO orion_app;
GRANT UPDATE (email_verified_at, locale) ON user_account TO orion_app;
GRANT SELECT, INSERT, UPDATE ON user_account TO orion_platform;

GRANT SELECT, INSERT ON tenant_member TO orion_app;
GRANT SELECT, INSERT, UPDATE ON tenant_member TO orion_platform;

GRANT SELECT, INSERT ON refresh_token TO orion_app;
GRANT UPDATE (used_at, revoked_at) ON refresh_token TO orion_app;
GRANT SELECT, DELETE ON refresh_token TO orion_platform; -- the purge job

-- The worker mints verification tokens (so no secret waits in the job queue); the API consumes them.
GRANT SELECT ON email_verification TO orion_app;
GRANT UPDATE (used_at) ON email_verification TO orion_app;
GRANT SELECT, INSERT, DELETE ON email_verification TO orion_platform;

-- The only query that runs before a tenant is known: find a user and their tenants by email, for
-- login. SECURITY DEFINER lets it read what row-level security hides from orion_app, so it takes
-- one argument, returns one row at most and checks nothing else. It relies on the schema owner
-- (who runs migrations) not being subject to row-level security on its own tables, which
-- orion serve already requires of the app role the other way round.
-- +goose StatementBegin
CREATE FUNCTION auth_find_user(p_email text)
    RETURNS TABLE (id uuid, password_hash text, email_verified_at timestamptz, locale text, tenant_ids uuid[])
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path = public, pg_temp
AS $$
    SELECT u.id, u.password_hash, u.email_verified_at, u.locale,
           array(SELECT m.tenant_id FROM tenant_member m WHERE m.user_id = u.id ORDER BY m.tenant_id)
    FROM user_account u
    WHERE u.email = lower(btrim(p_email))
$$;
-- +goose StatementEnd
REVOKE ALL ON FUNCTION auth_find_user(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION auth_find_user(text) TO orion_app, orion_platform;

-- +goose Down
DROP FUNCTION auth_find_user(text);
DROP TABLE email_verification;
DROP TABLE refresh_token;
-- Its policies read tenant_member, and tenant_member points back at it.
DROP TABLE user_account CASCADE;
DROP TABLE tenant_member;
