// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CashRoundingMode string

const (
	CashRoundingModeNearest CashRoundingMode = "nearest"
	CashRoundingModeDown    CashRoundingMode = "down"
	CashRoundingModeUp      CashRoundingMode = "up"
)

func (e *CashRoundingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CashRoundingMode(s)
	case string:
		*e = CashRoundingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CashRoundingMode: %T", src)
	}
	return nil
}

type NullCashRoundingMode struct {
	CashRoundingMode CashRoundingMode
	Valid            bool // Valid is true if CashRoundingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCashRoundingMode) Scan(value interface{}) error {
	if value == nil {
		ns.CashRoundingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CashRoundingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCashRoundingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CashRoundingMode), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusEarlyAccess SubscriptionStatus = "early_access"
	SubscriptionStatusTrialing    SubscriptionStatus = "trialing"
	SubscriptionStatusActive      SubscriptionStatus = "active"
	SubscriptionStatusPastDue     SubscriptionStatus = "past_due"
	SubscriptionStatusGrace       SubscriptionStatus = "grace"
	SubscriptionStatusReadOnly    SubscriptionStatus = "read_only"
	SubscriptionStatusCanceled    SubscriptionStatus = "canceled"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus
	Valid              bool // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type ChangeLog struct {
	TenantID   uuid.UUID
	Seq        int64
	EntityType string
	EntityID   uuid.UUID
	Op         string
	OutletID   *uuid.UUID
	CreatedAt  time.Time
}

type Outlet struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	Code       string
	Address    string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type OutletSetting struct {
	OutletID             uuid.UUID
	TenantID             uuid.UUID
	Timezone             string
	BusinessDayCutoff    pgtype.Time
	PriceIncludesTax     bool
	TaxRateBp            int32
	ServiceChargeRateBp  int32
	ServiceChargeTaxable bool
	CashRoundingUnit     int32
	CashRoundingMode     CashRoundingMode
	ReceiptHeader        string
	ReceiptFooter        string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Plan struct {
	ID        uuid.UUID
	Code      string
	Name      string
	IsPublic  bool
	CreatedAt time.Time
}

type Tenant struct {
	ID                 uuid.UUID
	Name               string
	Slug               string
	PlanID             uuid.UUID
	SubscriptionStatus SubscriptionStatus
	TrialEndsAt        *time.Time
	PaidUntil          *time.Time
	BillingStartsAt    *time.Time
	SuspendedAt        *time.Time
	ChangeSeq          int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
