// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOutletSettingsForUpdate = `-- name: GetOutletSettingsForUpdate :one
SELECT outlet_id, tenant_id, timezone, business_day_cutoff, price_includes_tax, tax_rate_bp, service_charge_rate_bp, service_charge_taxable, cash_rounding_unit, cash_rounding_mode, receipt_header, receipt_footer, created_at, updated_at FROM outlet_settings WHERE tenant_id = $1 AND outlet_id = $2 FOR UPDATE
`

type GetOutletSettingsForUpdateParams struct {
	TenantID uuid.UUID
	OutletID uuid.UUID
}

func (q *Queries) GetOutletSettingsForUpdate(ctx context.Context, arg GetOutletSettingsForUpdateParams) (OutletSetting, error) {
	row := q.db.QueryRow(ctx, getOutletSettingsForUpdate, arg.TenantID, arg.OutletID)
	var i OutletSetting
	err := row.Scan(
		&i.OutletID,
		&i.TenantID,
		&i.Timezone,
		&i.BusinessDayCutoff,
		&i.PriceIncludesTax,
		&i.TaxRateBp,
		&i.ServiceChargeRateBp,
		&i.ServiceChargeTaxable,
		&i.CashRoundingUnit,
		&i.CashRoundingMode,
		&i.ReceiptHeader,
		&i.ReceiptFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutletWithSettings = `-- name: GetOutletWithSettings :one
SELECT o.id, o.tenant_id, o.name, o.code, o.address, o.archived_at, o.created_at, o.updated_at, s.outlet_id, s.tenant_id, s.timezone, s.business_day_cutoff, s.price_includes_tax, s.tax_rate_bp, s.service_charge_rate_bp, s.service_charge_taxable, s.cash_rounding_unit, s.cash_rounding_mode, s.receipt_header, s.receipt_footer, s.created_at, s.updated_at
FROM outlet o
JOIN outlet_settings s ON s.tenant_id = o.tenant_id AND s.outlet_id = o.id
WHERE o.tenant_id = $1 AND o.id = $2
`

type GetOutletWithSettingsParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetOutletWithSettingsRow struct {
	Outlet        Outlet
	OutletSetting OutletSetting
}

func (q *Queries) GetOutletWithSettings(ctx context.Context, arg GetOutletWithSettingsParams) (GetOutletWithSettingsRow, error) {
	row := q.db.QueryRow(ctx, getOutletWithSettings, arg.TenantID, arg.ID)
	var i GetOutletWithSettingsRow
	err := row.Scan(
		&i.Outlet.ID,
		&i.Outlet.TenantID,
		&i.Outlet.Name,
		&i.Outlet.Code,
		&i.Outlet.Address,
		&i.Outlet.ArchivedAt,
		&i.Outlet.CreatedAt,
		&i.Outlet.UpdatedAt,
		&i.OutletSetting.OutletID,
		&i.OutletSetting.TenantID,
		&i.OutletSetting.Timezone,
		&i.OutletSetting.BusinessDayCutoff,
		&i.OutletSetting.PriceIncludesTax,
		&i.OutletSetting.TaxRateBp,
		&i.OutletSetting.ServiceChargeRateBp,
		&i.OutletSetting.ServiceChargeTaxable,
		&i.OutletSetting.CashRoundingUnit,
		&i.OutletSetting.CashRoundingMode,
		&i.OutletSetting.ReceiptHeader,
		&i.OutletSetting.ReceiptFooter,
		&i.OutletSetting.CreatedAt,
		&i.OutletSetting.UpdatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, plan_id, subscription_status, trial_ends_at, paid_until, billing_starts_at, suspended_at, change_seq, created_at, updated_at FROM tenant WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.PaidUntil,
		&i.BillingStartsAt,
		&i.SuspendedAt,
		&i.ChangeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one

SELECT id, name, slug, plan_id, subscription_status, trial_ends_at, paid_until, billing_starts_at, suspended_at, change_seq, created_at, updated_at FROM tenant WHERE slug = $1
`

// Queries below run as orion_platform, from operator tooling.
func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.PaidUntil,
		&i.BillingStartsAt,
		&i.SuspendedAt,
		&i.ChangeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantPlanCode = `-- name: GetTenantPlanCode :one

SELECT p.code FROM tenant t JOIN plan p ON p.id = t.plan_id WHERE t.id = $1
`

// Operator tooling (admin.go), as orion_platform.
func (q *Queries) GetTenantPlanCode(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTenantPlanCode, id)
	var code string
	err := row.Scan(&code)
	return code, err
}

const insertOutlet = `-- name: InsertOutlet :one
INSERT INTO outlet (id, tenant_id, name, code, address)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, code, address, archived_at, created_at, updated_at
`

type InsertOutletParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Code     string
	Address  string
}

func (q *Queries) InsertOutlet(ctx context.Context, arg InsertOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, insertOutlet,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.Address,
	)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutletSettings = `-- name: InsertOutletSettings :one
INSERT INTO outlet_settings (outlet_id, tenant_id, timezone)
VALUES ($1, $2, $3)
RETURNING outlet_id, tenant_id, timezone, business_day_cutoff, price_includes_tax, tax_rate_bp, service_charge_rate_bp, service_charge_taxable, cash_rounding_unit, cash_rounding_mode, receipt_header, receipt_footer, created_at, updated_at
`

type InsertOutletSettingsParams struct {
	OutletID uuid.UUID
	TenantID uuid.UUID
	Timezone string
}

func (q *Queries) InsertOutletSettings(ctx context.Context, arg InsertOutletSettingsParams) (OutletSetting, error) {
	row := q.db.QueryRow(ctx, insertOutletSettings, arg.OutletID, arg.TenantID, arg.Timezone)
	var i OutletSetting
	err := row.Scan(
		&i.OutletID,
		&i.TenantID,
		&i.Timezone,
		&i.BusinessDayCutoff,
		&i.PriceIncludesTax,
		&i.TaxRateBp,
		&i.ServiceChargeRateBp,
		&i.ServiceChargeTaxable,
		&i.CashRoundingUnit,
		&i.CashRoundingMode,
		&i.ReceiptHeader,
		&i.ReceiptFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO tenant (id, name, slug, plan_id, subscription_status)
SELECT $1, $2, $3, p.id,
       CASE WHEN p.code = 'early_access' THEN 'early_access' ELSE 'active' END::subscription_status
FROM plan p
WHERE p.code = $4
RETURNING id, name, slug, plan_id, subscription_status, trial_ends_at, paid_until, billing_starts_at, suspended_at, change_seq, created_at, updated_at
`

type InsertTenantParams struct {
	ID       uuid.UUID
	Name     string
	Slug     string
	PlanCode string
}

// Early access tenants have the early_access status (ADR 0007); any other plan starts active.
func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, insertTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.PlanCode,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.PaidUntil,
		&i.BillingStartsAt,
		&i.SuspendedAt,
		&i.ChangeSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOutletsWithSettings = `-- name: ListOutletsWithSettings :many

SELECT o.id, o.tenant_id, o.name, o.code, o.address, o.archived_at, o.created_at, o.updated_at, s.outlet_id, s.tenant_id, s.timezone, s.business_day_cutoff, s.price_includes_tax, s.tax_rate_bp, s.service_charge_rate_bp, s.service_charge_taxable, s.cash_rounding_unit, s.cash_rounding_mode, s.receipt_header, s.receipt_footer, s.created_at, s.updated_at
FROM outlet o
JOIN outlet_settings s ON s.tenant_id = o.tenant_id AND s.outlet_id = o.id
WHERE o.tenant_id = $1 AND o.archived_at IS NULL
ORDER BY o.code
`

type ListOutletsWithSettingsRow struct {
	Outlet        Outlet
	OutletSetting OutletSetting
}

// Outlets come back joined with their settings in one query, never one query per outlet.
func (q *Queries) ListOutletsWithSettings(ctx context.Context, tenantID uuid.UUID) ([]ListOutletsWithSettingsRow, error) {
	rows, err := q.db.Query(ctx, listOutletsWithSettings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutletsWithSettingsRow
	for rows.Next() {
		var i ListOutletsWithSettingsRow
		if err := rows.Scan(
			&i.Outlet.ID,
			&i.Outlet.TenantID,
			&i.Outlet.Name,
			&i.Outlet.Code,
			&i.Outlet.Address,
			&i.Outlet.ArchivedAt,
			&i.Outlet.CreatedAt,
			&i.Outlet.UpdatedAt,
			&i.OutletSetting.OutletID,
			&i.OutletSetting.TenantID,
			&i.OutletSetting.Timezone,
			&i.OutletSetting.BusinessDayCutoff,
			&i.OutletSetting.PriceIncludesTax,
			&i.OutletSetting.TaxRateBp,
			&i.OutletSetting.ServiceChargeRateBp,
			&i.OutletSetting.ServiceChargeTaxable,
			&i.OutletSetting.CashRoundingUnit,
			&i.OutletSetting.CashRoundingMode,
			&i.OutletSetting.ReceiptHeader,
			&i.OutletSetting.ReceiptFooter,
			&i.OutletSetting.CreatedAt,
			&i.OutletSetting.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordChange = `-- name: RecordChange :one
SELECT record_change($1::text, $2::uuid, $3::text, $4::uuid)::bigint AS seq
`

type RecordChangeParams struct {
	EntityType string
	EntityID   uuid.UUID
	Op         string
	OutletID   *uuid.UUID
}

func (q *Queries) RecordChange(ctx context.Context, arg RecordChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordChange,
		arg.EntityType,
		arg.EntityID,
		arg.Op,
		arg.OutletID,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const setTenantPlan = `-- name: SetTenantPlan :execrows
UPDATE tenant
SET plan_id = p.id,
    subscription_status = CASE WHEN p.code = 'early_access' THEN 'early_access' ELSE 'active' END::subscription_status
FROM plan p
WHERE tenant.id = $1 AND p.code = $2
`

type SetTenantPlanParams struct {
	ID       uuid.UUID
	PlanCode string
}

// Moving to early_access also restores its status; any other plan is an active subscription until
// billing (Phase 5) says otherwise.
func (q *Queries) SetTenantPlan(ctx context.Context, arg SetTenantPlanParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantPlan, arg.ID, arg.PlanCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTenantSuspended = `-- name: SetTenantSuspended :exec
UPDATE tenant SET suspended_at = $1 WHERE id = $2
`

type SetTenantSuspendedParams struct {
	SuspendedAt *time.Time
	ID          uuid.UUID
}

func (q *Queries) SetTenantSuspended(ctx context.Context, arg SetTenantSuspendedParams) error {
	_, err := q.db.Exec(ctx, setTenantSuspended, arg.SuspendedAt, arg.ID)
	return err
}

const updateOutletSettings = `-- name: UpdateOutletSettings :one
UPDATE outlet_settings
SET timezone = $1, business_day_cutoff = $2, price_includes_tax = $3,
    tax_rate_bp = $4, service_charge_rate_bp = $5,
    service_charge_taxable = $6, cash_rounding_unit = $7,
    cash_rounding_mode = $8, receipt_header = $9, receipt_footer = $10
WHERE tenant_id = $11 AND outlet_id = $12
RETURNING outlet_id, tenant_id, timezone, business_day_cutoff, price_includes_tax, tax_rate_bp, service_charge_rate_bp, service_charge_taxable, cash_rounding_unit, cash_rounding_mode, receipt_header, receipt_footer, created_at, updated_at
`

type UpdateOutletSettingsParams struct {
	Timezone             string
	BusinessDayCutoff    pgtype.Time
	PriceIncludesTax     bool
	TaxRateBp            int32
	ServiceChargeRateBp  int32
	ServiceChargeTaxable bool
	CashRoundingUnit     int32
	CashRoundingMode     CashRoundingMode
	ReceiptHeader        string
	ReceiptFooter        string
	TenantID             uuid.UUID
	OutletID             uuid.UUID
}

func (q *Queries) UpdateOutletSettings(ctx context.Context, arg UpdateOutletSettingsParams) (OutletSetting, error) {
	row := q.db.QueryRow(ctx, updateOutletSettings,
		arg.Timezone,
		arg.BusinessDayCutoff,
		arg.PriceIncludesTax,
		arg.TaxRateBp,
		arg.ServiceChargeRateBp,
		arg.ServiceChargeTaxable,
		arg.CashRoundingUnit,
		arg.CashRoundingMode,
		arg.ReceiptHeader,
		arg.ReceiptFooter,
		arg.TenantID,
		arg.OutletID,
	)
	var i OutletSetting
	err := row.Scan(
		&i.OutletID,
		&i.TenantID,
		&i.Timezone,
		&i.BusinessDayCutoff,
		&i.PriceIncludesTax,
		&i.TaxRateBp,
		&i.ServiceChargeRateBp,
		&i.ServiceChargeTaxable,
		&i.CashRoundingUnit,
		&i.CashRoundingMode,
		&i.ReceiptHeader,
		&i.ReceiptFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
