// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const catalogChangesBefore = `-- name: CatalogChangesBefore :many
SELECT DISTINCT entity_type, entity_id FROM change_log
WHERE tenant_id = $1 AND seq > $2 AND created_at <= $3
  AND ((entity_type = 'item' AND entity_id = ANY($4::uuid[]))
    OR (entity_type = 'outlet_variant' AND outlet_id = $5 AND entity_id = ANY($6::uuid[])))
`

type CatalogChangesBeforeParams struct {
	TenantID   uuid.UUID
	AfterSeq   int64
	At         time.Time
	ItemIds    []uuid.UUID
	OutletID   *uuid.UUID
	VariantIds []uuid.UUID
}

type CatalogChangesBeforeRow struct {
	EntityType string
	EntityID   uuid.UUID
}

// Changes to these items, or to these variants at this outlet, that were made after the device's
// catalog cursor but before the sale happened: updates the device could have had and did not.
func (q *Queries) CatalogChangesBefore(ctx context.Context, arg CatalogChangesBeforeParams) ([]CatalogChangesBeforeRow, error) {
	rows, err := q.db.Query(ctx, catalogChangesBefore,
		arg.TenantID,
		arg.AfterSeq,
		arg.At,
		arg.ItemIds,
		arg.OutletID,
		arg.VariantIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogChangesBeforeRow
	for rows.Next() {
		var i CatalogChangesBeforeRow
		if err := rows.Scan(&i.EntityType, &i.EntityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countVariants = `-- name: CountVariants :one
SELECT count(*) FROM variant WHERE tenant_id = $1 AND item_id = $2
`

type CountVariantsParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
}

func (q *Queries) CountVariants(ctx context.Context, arg CountVariantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVariants, arg.TenantID, arg.ItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteItemModifierGroups = `-- name: DeleteItemModifierGroups :exec
DELETE FROM item_modifier_group WHERE tenant_id = $1 AND item_id = $2
`

type DeleteItemModifierGroupsParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
}

func (q *Queries) DeleteItemModifierGroups(ctx context.Context, arg DeleteItemModifierGroupsParams) error {
	_, err := q.db.Exec(ctx, deleteItemModifierGroups, arg.TenantID, arg.ItemID)
	return err
}

const effectivePrices = `-- name: EffectivePrices :many

SELECT v.id, v.item_id, coalesce(ov.price_override, v.base_price)::bigint AS price
FROM variant v
LEFT JOIN outlet_variant ov ON ov.tenant_id = v.tenant_id AND ov.variant_id = v.id AND ov.outlet_id = $1
WHERE v.tenant_id = $2 AND v.id = ANY($3::uuid[])
`

type EffectivePricesParams struct {
	OutletID   uuid.UUID
	TenantID   uuid.UUID
	VariantIds []uuid.UUID
}

type EffectivePricesRow struct {
	ID     uuid.UUID
	ItemID uuid.UUID
	Price  int64
}

// Price checks for the sales projector (internal/sales), inside the event's transaction.
// What each variant costs at an outlet now: its override there, or its base price.
func (q *Queries) EffectivePrices(ctx context.Context, arg EffectivePricesParams) ([]EffectivePricesRow, error) {
	rows, err := q.db.Query(ctx, effectivePrices, arg.OutletID, arg.TenantID, arg.VariantIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EffectivePricesRow
	for rows.Next() {
		var i EffectivePricesRow
		if err := rows.Scan(&i.ID, &i.ItemID, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryForUpdate = `-- name: GetCategoryForUpdate :one
SELECT id, tenant_id, name, sort_order, archived_at, created_at, updated_at FROM category WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetCategoryForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetCategoryForUpdate(ctx context.Context, arg GetCategoryForUpdateParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryForUpdate, arg.TenantID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, tenant_id, category_id, name, sku, barcode, image_url, track_stock, archived_at, created_at, updated_at FROM item WHERE tenant_id = $1 AND id = $2
`

type GetItemParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, arg.TenantID, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.TrackStock,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemForUpdate = `-- name: GetItemForUpdate :one
SELECT id, tenant_id, category_id, name, sku, barcode, image_url, track_stock, archived_at, created_at, updated_at FROM item WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetItemForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetItemForUpdate(ctx context.Context, arg GetItemForUpdateParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItemForUpdate, arg.TenantID, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.TrackStock,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModifierForUpdate = `-- name: GetModifierForUpdate :one
SELECT id, tenant_id, group_id, name, price_delta, sort_order, archived_at, created_at, updated_at FROM modifier WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetModifierForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetModifierForUpdate(ctx context.Context, arg GetModifierForUpdateParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, getModifierForUpdate, arg.TenantID, arg.ID)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GroupID,
		&i.Name,
		&i.PriceDelta,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModifierGroupForUpdate = `-- name: GetModifierGroupForUpdate :one
SELECT id, tenant_id, name, min_select, max_select, required, archived_at, created_at, updated_at FROM modifier_group WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetModifierGroupForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetModifierGroupForUpdate(ctx context.Context, arg GetModifierGroupForUpdateParams) (ModifierGroup, error) {
	row := q.db.QueryRow(ctx, getModifierGroupForUpdate, arg.TenantID, arg.ID)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.MinSelect,
		&i.MaxSelect,
		&i.Required,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutletVariantForUpdate = `-- name: GetOutletVariantForUpdate :one

SELECT tenant_id, outlet_id, variant_id, price_override, available, created_at, updated_at FROM outlet_variant WHERE tenant_id = $1 AND outlet_id = $2 AND variant_id = $3 FOR UPDATE
`

type GetOutletVariantForUpdateParams struct {
	TenantID  uuid.UUID
	OutletID  uuid.UUID
	VariantID uuid.UUID
}

// Per-outlet prices and availability
func (q *Queries) GetOutletVariantForUpdate(ctx context.Context, arg GetOutletVariantForUpdateParams) (OutletVariant, error) {
	row := q.db.QueryRow(ctx, getOutletVariantForUpdate, arg.TenantID, arg.OutletID, arg.VariantID)
	var i OutletVariant
	err := row.Scan(
		&i.TenantID,
		&i.OutletID,
		&i.VariantID,
		&i.PriceOverride,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantForUpdate = `-- name: GetVariantForUpdate :one
SELECT id, tenant_id, item_id, name, sku, barcode, base_price, sort_order, archived_at, created_at, updated_at FROM variant WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetVariantForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetVariantForUpdate(ctx context.Context, arg GetVariantForUpdateParams) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariantForUpdate, arg.TenantID, arg.ID)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ItemID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.BasePrice,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one

INSERT INTO category (id, tenant_id, name, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, sort_order, archived_at, created_at, updated_at
`

type InsertCategoryParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	SortOrder int32
}

// Categories
func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :one

INSERT INTO item (id, tenant_id, category_id, name, sku, barcode, image_url, track_stock)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, category_id, name, sku, barcode, image_url, track_stock, archived_at, created_at, updated_at
`

type InsertItemParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	CategoryID *uuid.UUID
	Name       string
	Sku        *string
	Barcode    *string
	ImageUrl   *string
	TrackStock bool
}

// Items
func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, insertItem,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.Sku,
		arg.Barcode,
		arg.ImageUrl,
		arg.TrackStock,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.TrackStock,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertItemModifierGroups = `-- name: InsertItemModifierGroups :exec
INSERT INTO item_modifier_group (tenant_id, item_id, group_id, sort_order)
SELECT $1::uuid, $2::uuid, g.id, (g.n - 1)::integer
FROM unnest($3::uuid[]) WITH ORDINALITY AS g(id, n)
`

type InsertItemModifierGroupsParams struct {
	TenantID uuid.UUID
	ItemID   uuid.UUID
	GroupIds []uuid.UUID
}

// Display order follows the order of the ids given.
func (q *Queries) InsertItemModifierGroups(ctx context.Context, arg InsertItemModifierGroupsParams) error {
	_, err := q.db.Exec(ctx, insertItemModifierGroups, arg.TenantID, arg.ItemID, arg.GroupIds)
	return err
}

const insertModifier = `-- name: InsertModifier :one
INSERT INTO modifier (id, tenant_id, group_id, name, price_delta, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, group_id, name, price_delta, sort_order, archived_at, created_at, updated_at
`

type InsertModifierParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	GroupID    uuid.UUID
	Name       string
	PriceDelta int64
	SortOrder  int32
}

func (q *Queries) InsertModifier(ctx context.Context, arg InsertModifierParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, insertModifier,
		arg.ID,
		arg.TenantID,
		arg.GroupID,
		arg.Name,
		arg.PriceDelta,
		arg.SortOrder,
	)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GroupID,
		&i.Name,
		&i.PriceDelta,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertModifierGroup = `-- name: InsertModifierGroup :one

INSERT INTO modifier_group (id, tenant_id, name, min_select, max_select, required)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, min_select, max_select, required, archived_at, created_at, updated_at
`

type InsertModifierGroupParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	MinSelect int32
	MaxSelect int32
	Required  bool
}

// Modifier groups and modifiers
func (q *Queries) InsertModifierGroup(ctx context.Context, arg InsertModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRow(ctx, insertModifierGroup,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.MinSelect,
		arg.MaxSelect,
		arg.Required,
	)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.MinSelect,
		&i.MaxSelect,
		&i.Required,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertModifiers = `-- name: InsertModifiers :many
INSERT INTO modifier (id, tenant_id, group_id, name, price_delta, sort_order)
SELECT a.id, $1::uuid, $2::uuid, b.name, c.price_delta, (a.n - 1)::integer
FROM unnest($3::uuid[]) WITH ORDINALITY AS a(id, n)
JOIN unnest($4::text[]) WITH ORDINALITY AS b(name, n) ON b.n = a.n
JOIN unnest($5::bigint[]) WITH ORDINALITY AS c(price_delta, n) ON c.n = a.n
RETURNING id, tenant_id, group_id, name, price_delta, sort_order, archived_at, created_at, updated_at
`

type InsertModifiersParams struct {
	TenantID    uuid.UUID
	GroupID     uuid.UUID
	Ids         []uuid.UUID
	Names       []string
	PriceDeltas []int64
}

func (q *Queries) InsertModifiers(ctx context.Context, arg InsertModifiersParams) ([]Modifier, error) {
	rows, err := q.db.Query(ctx, insertModifiers,
		arg.TenantID,
		arg.GroupID,
		arg.Ids,
		arg.Names,
		arg.PriceDeltas,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modifier
	for rows.Next() {
		var i Modifier
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GroupID,
			&i.Name,
			&i.PriceDelta,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVariant = `-- name: InsertVariant :one

INSERT INTO variant (id, tenant_id, item_id, name, sku, barcode, base_price, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, item_id, name, sku, barcode, base_price, sort_order, archived_at, created_at, updated_at
`

type InsertVariantParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ItemID    uuid.UUID
	Name      string
	Sku       *string
	Barcode   *string
	BasePrice int64
	SortOrder int32
}

// Variants
func (q *Queries) InsertVariant(ctx context.Context, arg InsertVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, insertVariant,
		arg.ID,
		arg.TenantID,
		arg.ItemID,
		arg.Name,
		arg.Sku,
		arg.Barcode,
		arg.BasePrice,
		arg.SortOrder,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ItemID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.BasePrice,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVariants = `-- name: InsertVariants :many

INSERT INTO variant (id, tenant_id, item_id, name, sku, barcode, base_price, sort_order)
SELECT a.id, $1::uuid, $2::uuid, b.name, NULLIF(c.sku, ''), NULLIF(d.barcode, ''), e.base_price, (a.n - 1)::integer
FROM unnest($3::uuid[]) WITH ORDINALITY AS a(id, n)
JOIN unnest($4::text[]) WITH ORDINALITY AS b(name, n) ON b.n = a.n
JOIN unnest($5::text[]) WITH ORDINALITY AS c(sku, n) ON c.n = a.n
JOIN unnest($6::text[]) WITH ORDINALITY AS d(barcode, n) ON d.n = a.n
JOIN unnest($7::bigint[]) WITH ORDINALITY AS e(base_price, n) ON e.n = a.n
RETURNING id, tenant_id, item_id, name, sku, barcode, base_price, sort_order, archived_at, created_at, updated_at
`

type InsertVariantsParams struct {
	TenantID   uuid.UUID
	ItemID     uuid.UUID
	Ids        []uuid.UUID
	Names      []string
	Skus       []string
	Barcodes   []string
	BasePrices []int64
}

// Bulk inserts: one statement however many rows (BACKEND_PLAN.md section 4.12). Empty strings in
// the optional columns become NULL. Position in the arrays is the display order.
func (q *Queries) InsertVariants(ctx context.Context, arg InsertVariantsParams) ([]Variant, error) {
	rows, err := q.db.Query(ctx, insertVariants,
		arg.TenantID,
		arg.ItemID,
		arg.Ids,
		arg.Names,
		arg.Skus,
		arg.Barcodes,
		arg.BasePrices,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variant
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ItemID,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.BasePrice,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, tenant_id, name, sort_order, archived_at, created_at, updated_at FROM category WHERE tenant_id = $1 ORDER BY id
`

func (q *Queries) ListAllCategories(ctx context.Context, tenantID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listAllCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllItems = `-- name: ListAllItems :many
SELECT id, tenant_id, category_id, name, sku, barcode, image_url, track_stock, archived_at, created_at, updated_at FROM item WHERE tenant_id = $1 ORDER BY id
`

func (q *Queries) ListAllItems(ctx context.Context, tenantID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listAllItems, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.TrackStock,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllModifierGroups = `-- name: ListAllModifierGroups :many
SELECT id, tenant_id, name, min_select, max_select, required, archived_at, created_at, updated_at FROM modifier_group WHERE tenant_id = $1 ORDER BY id
`

func (q *Queries) ListAllModifierGroups(ctx context.Context, tenantID uuid.UUID) ([]ModifierGroup, error) {
	rows, err := q.db.Query(ctx, listAllModifierGroups, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModifierGroup
	for rows.Next() {
		var i ModifierGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.MinSelect,
			&i.MaxSelect,
			&i.Required,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOutletVariants = `-- name: ListAllOutletVariants :many
SELECT tenant_id, outlet_id, variant_id, price_override, available, created_at, updated_at FROM outlet_variant WHERE tenant_id = $1 AND outlet_id = $2 ORDER BY variant_id
`

type ListAllOutletVariantsParams struct {
	TenantID uuid.UUID
	OutletID uuid.UUID
}

func (q *Queries) ListAllOutletVariants(ctx context.Context, arg ListAllOutletVariantsParams) ([]OutletVariant, error) {
	rows, err := q.db.Query(ctx, listAllOutletVariants, arg.TenantID, arg.OutletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutletVariant
	for rows.Next() {
		var i OutletVariant
		if err := rows.Scan(
			&i.TenantID,
			&i.OutletID,
			&i.VariantID,
			&i.PriceOverride,
			&i.Available,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, tenant_id, name, sort_order, archived_at, created_at, updated_at FROM category
WHERE tenant_id = $1 AND id > $2 AND ($3::boolean OR archived_at IS NULL)
ORDER BY id
LIMIT $4
`

type ListCategoriesParams struct {
	TenantID        uuid.UUID
	After           uuid.UUID
	IncludeArchived bool
	PageSize        int32
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories,
		arg.TenantID,
		arg.After,
		arg.IncludeArchived,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByIDs = `-- name: ListCategoriesByIDs :many

SELECT id, tenant_id, name, sort_order, archived_at, created_at, updated_at FROM category WHERE tenant_id = $1 AND id = ANY($2::uuid[]) ORDER BY id
`

type ListCategoriesByIDsParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

// The POS pull (internal/sync): current state of what changed, or of everything.
func (q *Queries) ListCategoriesByIDs(ctx context.Context, arg ListCategoriesByIDsParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemModifierGroups = `-- name: ListItemModifierGroups :many

SELECT item_id, group_id FROM item_modifier_group
WHERE tenant_id = $1 AND item_id = ANY($2::uuid[])
ORDER BY item_id, sort_order, group_id
`

type ListItemModifierGroupsParams struct {
	TenantID uuid.UUID
	ItemIds  []uuid.UUID
}

type ListItemModifierGroupsRow struct {
	ItemID  uuid.UUID
	GroupID uuid.UUID
}

// Which modifier groups an item offers
// The group links of a page of items, in one query.
func (q *Queries) ListItemModifierGroups(ctx context.Context, arg ListItemModifierGroupsParams) ([]ListItemModifierGroupsRow, error) {
	rows, err := q.db.Query(ctx, listItemModifierGroups, arg.TenantID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemModifierGroupsRow
	for rows.Next() {
		var i ListItemModifierGroupsRow
		if err := rows.Scan(&i.ItemID, &i.GroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, tenant_id, category_id, name, sku, barcode, image_url, track_stock, archived_at, created_at, updated_at FROM item
WHERE tenant_id = $1 AND id > $2
  AND ($3::boolean OR archived_at IS NULL)
  AND ($4::uuid IS NULL OR category_id = $4)
ORDER BY id
LIMIT $5
`

type ListItemsParams struct {
	TenantID        uuid.UUID
	After           uuid.UUID
	IncludeArchived bool
	CategoryID      *uuid.UUID
	PageSize        int32
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.TenantID,
		arg.After,
		arg.IncludeArchived,
		arg.CategoryID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.TrackStock,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByIDs = `-- name: ListItemsByIDs :many
SELECT id, tenant_id, category_id, name, sku, barcode, image_url, track_stock, archived_at, created_at, updated_at FROM item WHERE tenant_id = $1 AND id = ANY($2::uuid[]) ORDER BY id
`

type ListItemsByIDsParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) ListItemsByIDs(ctx context.Context, arg ListItemsByIDsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.TrackStock,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifierGroups = `-- name: ListModifierGroups :many
SELECT id, tenant_id, name, min_select, max_select, required, archived_at, created_at, updated_at FROM modifier_group
WHERE tenant_id = $1 AND id > $2 AND ($3::boolean OR archived_at IS NULL)
ORDER BY id
LIMIT $4
`

type ListModifierGroupsParams struct {
	TenantID        uuid.UUID
	After           uuid.UUID
	IncludeArchived bool
	PageSize        int32
}

func (q *Queries) ListModifierGroups(ctx context.Context, arg ListModifierGroupsParams) ([]ModifierGroup, error) {
	rows, err := q.db.Query(ctx, listModifierGroups,
		arg.TenantID,
		arg.After,
		arg.IncludeArchived,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModifierGroup
	for rows.Next() {
		var i ModifierGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.MinSelect,
			&i.MaxSelect,
			&i.Required,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifierGroupsByIDs = `-- name: ListModifierGroupsByIDs :many
SELECT id, tenant_id, name, min_select, max_select, required, archived_at, created_at, updated_at FROM modifier_group WHERE tenant_id = $1 AND id = ANY($2::uuid[]) ORDER BY id
`

type ListModifierGroupsByIDsParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) ListModifierGroupsByIDs(ctx context.Context, arg ListModifierGroupsByIDsParams) ([]ModifierGroup, error) {
	rows, err := q.db.Query(ctx, listModifierGroupsByIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModifierGroup
	for rows.Next() {
		var i ModifierGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.MinSelect,
			&i.MaxSelect,
			&i.Required,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifiersByGroups = `-- name: ListModifiersByGroups :many
SELECT id, tenant_id, group_id, name, price_delta, sort_order, archived_at, created_at, updated_at FROM modifier
WHERE tenant_id = $1 AND group_id = ANY($2::uuid[])
ORDER BY group_id, sort_order, id
`

type ListModifiersByGroupsParams struct {
	TenantID uuid.UUID
	GroupIds []uuid.UUID
}

// The modifiers of a page of groups, in one query.
func (q *Queries) ListModifiersByGroups(ctx context.Context, arg ListModifiersByGroupsParams) ([]Modifier, error) {
	rows, err := q.db.Query(ctx, listModifiersByGroups, arg.TenantID, arg.GroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modifier
	for rows.Next() {
		var i Modifier
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GroupID,
			&i.Name,
			&i.PriceDelta,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutletVariants = `-- name: ListOutletVariants :many
SELECT tenant_id, outlet_id, variant_id, price_override, available, created_at, updated_at FROM outlet_variant
WHERE tenant_id = $1 AND outlet_id = $2 AND variant_id > $3
ORDER BY variant_id
LIMIT $4
`

type ListOutletVariantsParams struct {
	TenantID uuid.UUID
	OutletID uuid.UUID
	After    uuid.UUID
	PageSize int32
}

func (q *Queries) ListOutletVariants(ctx context.Context, arg ListOutletVariantsParams) ([]OutletVariant, error) {
	rows, err := q.db.Query(ctx, listOutletVariants,
		arg.TenantID,
		arg.OutletID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutletVariant
	for rows.Next() {
		var i OutletVariant
		if err := rows.Scan(
			&i.TenantID,
			&i.OutletID,
			&i.VariantID,
			&i.PriceOverride,
			&i.Available,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutletVariantsByVariantIDs = `-- name: ListOutletVariantsByVariantIDs :many
SELECT tenant_id, outlet_id, variant_id, price_override, available, created_at, updated_at FROM outlet_variant
WHERE tenant_id = $1 AND outlet_id = $2 AND variant_id = ANY($3::uuid[])
ORDER BY variant_id
`

type ListOutletVariantsByVariantIDsParams struct {
	TenantID   uuid.UUID
	OutletID   uuid.UUID
	VariantIds []uuid.UUID
}

func (q *Queries) ListOutletVariantsByVariantIDs(ctx context.Context, arg ListOutletVariantsByVariantIDsParams) ([]OutletVariant, error) {
	rows, err := q.db.Query(ctx, listOutletVariantsByVariantIDs, arg.TenantID, arg.OutletID, arg.VariantIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutletVariant
	for rows.Next() {
		var i OutletVariant
		if err := rows.Scan(
			&i.TenantID,
			&i.OutletID,
			&i.VariantID,
			&i.PriceOverride,
			&i.Available,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByItems = `-- name: ListVariantsByItems :many
SELECT id, tenant_id, item_id, name, sku, barcode, base_price, sort_order, archived_at, created_at, updated_at FROM variant
WHERE tenant_id = $1 AND item_id = ANY($2::uuid[])
ORDER BY item_id, sort_order, id
`

type ListVariantsByItemsParams struct {
	TenantID uuid.UUID
	ItemIds  []uuid.UUID
}

// The variants of a page of items, in one query.
func (q *Queries) ListVariantsByItems(ctx context.Context, arg ListVariantsByItemsParams) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariantsByItems, arg.TenantID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variant
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ItemID,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.BasePrice,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE category SET name = $1, sort_order = $2, archived_at = $3
WHERE tenant_id = $4 AND id = $5
RETURNING id, tenant_id, name, sort_order, archived_at, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name       string
	SortOrder  int32
	ArchivedAt *time.Time
	TenantID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.SortOrder,
		arg.ArchivedAt,
		arg.TenantID,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE item
SET category_id = $1, name = $2, sku = $3, barcode = $4,
    image_url = $5, track_stock = $6, archived_at = $7
WHERE tenant_id = $8 AND id = $9
RETURNING id, tenant_id, category_id, name, sku, barcode, image_url, track_stock, archived_at, created_at, updated_at
`

type UpdateItemParams struct {
	CategoryID *uuid.UUID
	Name       string
	Sku        *string
	Barcode    *string
	ImageUrl   *string
	TrackStock bool
	ArchivedAt *time.Time
	TenantID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.CategoryID,
		arg.Name,
		arg.Sku,
		arg.Barcode,
		arg.ImageUrl,
		arg.TrackStock,
		arg.ArchivedAt,
		arg.TenantID,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.TrackStock,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModifier = `-- name: UpdateModifier :one
UPDATE modifier
SET name = $1, price_delta = $2, sort_order = $3, archived_at = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, group_id, name, price_delta, sort_order, archived_at, created_at, updated_at
`

type UpdateModifierParams struct {
	Name       string
	PriceDelta int64
	SortOrder  int32
	ArchivedAt *time.Time
	TenantID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateModifier(ctx context.Context, arg UpdateModifierParams) (Modifier, error) {
	row := q.db.QueryRow(ctx, updateModifier,
		arg.Name,
		arg.PriceDelta,
		arg.SortOrder,
		arg.ArchivedAt,
		arg.TenantID,
		arg.ID,
	)
	var i Modifier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GroupID,
		&i.Name,
		&i.PriceDelta,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModifierGroup = `-- name: UpdateModifierGroup :one
UPDATE modifier_group
SET name = $1, min_select = $2, max_select = $3, required = $4,
    archived_at = $5
WHERE tenant_id = $6 AND id = $7
RETURNING id, tenant_id, name, min_select, max_select, required, archived_at, created_at, updated_at
`

type UpdateModifierGroupParams struct {
	Name       string
	MinSelect  int32
	MaxSelect  int32
	Required   bool
	ArchivedAt *time.Time
	TenantID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateModifierGroup(ctx context.Context, arg UpdateModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRow(ctx, updateModifierGroup,
		arg.Name,
		arg.MinSelect,
		arg.MaxSelect,
		arg.Required,
		arg.ArchivedAt,
		arg.TenantID,
		arg.ID,
	)
	var i ModifierGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.MinSelect,
		&i.MaxSelect,
		&i.Required,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE variant
SET name = $1, sku = $2, barcode = $3, base_price = $4,
    sort_order = $5, archived_at = $6
WHERE tenant_id = $7 AND id = $8
RETURNING id, tenant_id, item_id, name, sku, barcode, base_price, sort_order, archived_at, created_at, updated_at
`

type UpdateVariantParams struct {
	Name       string
	Sku        *string
	Barcode    *string
	BasePrice  int64
	SortOrder  int32
	ArchivedAt *time.Time
	TenantID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.Name,
		arg.Sku,
		arg.Barcode,
		arg.BasePrice,
		arg.SortOrder,
		arg.ArchivedAt,
		arg.TenantID,
		arg.ID,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ItemID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.BasePrice,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOutletVariant = `-- name: UpsertOutletVariant :one
INSERT INTO outlet_variant (tenant_id, outlet_id, variant_id, price_override, available)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, outlet_id, variant_id)
DO UPDATE SET price_override = excluded.price_override, available = excluded.available
RETURNING tenant_id, outlet_id, variant_id, price_override, available, created_at, updated_at
`

type UpsertOutletVariantParams struct {
	TenantID      uuid.UUID
	OutletID      uuid.UUID
	VariantID     uuid.UUID
	PriceOverride *int64
	Available     bool
}

func (q *Queries) UpsertOutletVariant(ctx context.Context, arg UpsertOutletVariantParams) (OutletVariant, error) {
	row := q.db.QueryRow(ctx, upsertOutletVariant,
		arg.TenantID,
		arg.OutletID,
		arg.VariantID,
		arg.PriceOverride,
		arg.Available,
	)
	var i OutletVariant
	err := row.Scan(
		&i.TenantID,
		&i.OutletID,
		&i.VariantID,
		&i.PriceOverride,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
