// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getIngredientCategoryForUpdate = `-- name: GetIngredientCategoryForUpdate :one
SELECT id, tenant_id, name, default_transaction_type_id, description, archived_at, created_at, updated_at FROM ingredient_category WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetIngredientCategoryForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetIngredientCategoryForUpdate(ctx context.Context, arg GetIngredientCategoryForUpdateParams) (IngredientCategory, error) {
	row := q.db.QueryRow(ctx, getIngredientCategoryForUpdate, arg.TenantID, arg.ID)
	var i IngredientCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DefaultTransactionTypeID,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredientForUpdate = `-- name: GetIngredientForUpdate :one
SELECT id, tenant_id, name, category_id, uom_id, track, description, archived_at, created_at, updated_at FROM ingredient WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetIngredientForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetIngredientForUpdate(ctx context.Context, arg GetIngredientForUpdateParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientForUpdate, arg.TenantID, arg.ID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CategoryID,
		&i.UomID,
		&i.Track,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionTypeForUpdate = `-- name: GetTransactionTypeForUpdate :one
SELECT id, tenant_id, name, category, description, archived_at, created_at, updated_at FROM transaction_type WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetTransactionTypeForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetTransactionTypeForUpdate(ctx context.Context, arg GetTransactionTypeForUpdateParams) (TransactionType, error) {
	row := q.db.QueryRow(ctx, getTransactionTypeForUpdate, arg.TenantID, arg.ID)
	var i TransactionType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUomCategoryForUpdate = `-- name: GetUomCategoryForUpdate :one
SELECT id, tenant_id, name, archived_at, created_at, updated_at FROM uom_category WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetUomCategoryForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetUomCategoryForUpdate(ctx context.Context, arg GetUomCategoryForUpdateParams) (UomCategory, error) {
	row := q.db.QueryRow(ctx, getUomCategoryForUpdate, arg.TenantID, arg.ID)
	var i UomCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUomForIngredient = `-- name: GetUomForIngredient :one
SELECT u.id, u.category_id FROM uom u JOIN uom_category c ON c.tenant_id = u.tenant_id AND c.id = u.category_id
WHERE u.tenant_id = $1 AND u.id = $2 AND u.active AND c.archived_at IS NULL
`

type GetUomForIngredientParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetUomForIngredientRow struct {
	ID         uuid.UUID
	CategoryID uuid.UUID
}

// A unit an ingredient may be given: active, in a category that is not archived.
func (q *Queries) GetUomForIngredient(ctx context.Context, arg GetUomForIngredientParams) (GetUomForIngredientRow, error) {
	row := q.db.QueryRow(ctx, getUomForIngredient, arg.TenantID, arg.ID)
	var i GetUomForIngredientRow
	err := row.Scan(&i.ID, &i.CategoryID)
	return i, err
}

const insertIngredient = `-- name: InsertIngredient :one

INSERT INTO ingredient (id, tenant_id, name, category_id, uom_id, track, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, name, category_id, uom_id, track, description, archived_at, created_at, updated_at
`

type InsertIngredientParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	CategoryID  *uuid.UUID
	UomID       uuid.UUID
	Track       bool
	Description *string
}

// Ingredients
func (q *Queries) InsertIngredient(ctx context.Context, arg InsertIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, insertIngredient,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CategoryID,
		arg.UomID,
		arg.Track,
		arg.Description,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CategoryID,
		&i.UomID,
		&i.Track,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIngredientCategory = `-- name: InsertIngredientCategory :one

INSERT INTO ingredient_category (id, tenant_id, name, default_transaction_type_id, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, default_transaction_type_id, description, archived_at, created_at, updated_at
`

type InsertIngredientCategoryParams struct {
	ID                       uuid.UUID
	TenantID                 uuid.UUID
	Name                     string
	DefaultTransactionTypeID *uuid.UUID
	Description              *string
}

// Ingredient categories
func (q *Queries) InsertIngredientCategory(ctx context.Context, arg InsertIngredientCategoryParams) (IngredientCategory, error) {
	row := q.db.QueryRow(ctx, insertIngredientCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.DefaultTransactionTypeID,
		arg.Description,
	)
	var i IngredientCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DefaultTransactionTypeID,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTransactionType = `-- name: InsertTransactionType :one

INSERT INTO transaction_type (id, tenant_id, name, category, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, category, description, archived_at, created_at, updated_at
`

type InsertTransactionTypeParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Category    string
	Description *string
}

// Transaction types
func (q *Queries) InsertTransactionType(ctx context.Context, arg InsertTransactionTypeParams) (TransactionType, error) {
	row := q.db.QueryRow(ctx, insertTransactionType,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Category,
		arg.Description,
	)
	var i TransactionType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUomCategory = `-- name: InsertUomCategory :one

INSERT INTO uom_category (id, tenant_id, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, archived_at, created_at, updated_at
`

type InsertUomCategoryParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
}

// UoM categories and units
func (q *Queries) InsertUomCategory(ctx context.Context, arg InsertUomCategoryParams) (UomCategory, error) {
	row := q.db.QueryRow(ctx, insertUomCategory, arg.ID, arg.TenantID, arg.Name)
	var i UomCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUoms = `-- name: InsertUoms :exec
INSERT INTO uom (id, tenant_id, category_id, name, is_reference, ratio_num, ratio_den, rounding_scaled, active)
SELECT unnest($1::uuid[]), $2, $3, unnest($4::text[]), unnest($5::boolean[]),
       unnest($6::bigint[]), unnest($7::bigint[]), unnest($8::bigint[]), unnest($9::boolean[])
`

type InsertUomsParams struct {
	Ids            []uuid.UUID
	TenantID       uuid.UUID
	CategoryID     uuid.UUID
	Names          []string
	IsReference    []bool
	RatioNum       []int64
	RatioDen       []int64
	RoundingScaled []int64
	Active         []bool
}

func (q *Queries) InsertUoms(ctx context.Context, arg InsertUomsParams) error {
	_, err := q.db.Exec(ctx, insertUoms,
		arg.Ids,
		arg.TenantID,
		arg.CategoryID,
		arg.Names,
		arg.IsReference,
		arg.RatioNum,
		arg.RatioDen,
		arg.RoundingScaled,
		arg.Active,
	)
	return err
}

const listIngredientCategories = `-- name: ListIngredientCategories :many
SELECT id, tenant_id, name, default_transaction_type_id, description, archived_at, created_at, updated_at FROM ingredient_category
WHERE tenant_id = $1 AND id > $2 AND ($3::boolean OR archived_at IS NULL)
ORDER BY id
LIMIT $4
`

type ListIngredientCategoriesParams struct {
	TenantID        uuid.UUID
	After           uuid.UUID
	IncludeArchived bool
	PageSize        int32
}

func (q *Queries) ListIngredientCategories(ctx context.Context, arg ListIngredientCategoriesParams) ([]IngredientCategory, error) {
	rows, err := q.db.Query(ctx, listIngredientCategories,
		arg.TenantID,
		arg.After,
		arg.IncludeArchived,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientCategory
	for rows.Next() {
		var i IngredientCategory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DefaultTransactionTypeID,
			&i.Description,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, tenant_id, name, category_id, uom_id, track, description, archived_at, created_at, updated_at FROM ingredient
WHERE tenant_id = $1 AND id > $2 AND ($3::boolean OR archived_at IS NULL)
  AND ($4::uuid IS NULL OR category_id = $4)
ORDER BY id
LIMIT $5
`

type ListIngredientsParams struct {
	TenantID        uuid.UUID
	After           uuid.UUID
	IncludeArchived bool
	CategoryID      *uuid.UUID
	PageSize        int32
}

func (q *Queries) ListIngredients(ctx context.Context, arg ListIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients,
		arg.TenantID,
		arg.After,
		arg.IncludeArchived,
		arg.CategoryID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CategoryID,
			&i.UomID,
			&i.Track,
			&i.Description,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTypes = `-- name: ListTransactionTypes :many
SELECT id, tenant_id, name, category, description, archived_at, created_at, updated_at FROM transaction_type
WHERE tenant_id = $1 AND id > $2 AND ($3::boolean OR archived_at IS NULL)
ORDER BY id
LIMIT $4
`

type ListTransactionTypesParams struct {
	TenantID        uuid.UUID
	After           uuid.UUID
	IncludeArchived bool
	PageSize        int32
}

func (q *Queries) ListTransactionTypes(ctx context.Context, arg ListTransactionTypesParams) ([]TransactionType, error) {
	rows, err := q.db.Query(ctx, listTransactionTypes,
		arg.TenantID,
		arg.After,
		arg.IncludeArchived,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionType
	for rows.Next() {
		var i TransactionType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUomCategories = `-- name: ListUomCategories :many
SELECT id, tenant_id, name, archived_at, created_at, updated_at FROM uom_category
WHERE tenant_id = $1 AND id > $2 AND ($3::boolean OR archived_at IS NULL)
ORDER BY id
LIMIT $4
`

type ListUomCategoriesParams struct {
	TenantID        uuid.UUID
	After           uuid.UUID
	IncludeArchived bool
	PageSize        int32
}

func (q *Queries) ListUomCategories(ctx context.Context, arg ListUomCategoriesParams) ([]UomCategory, error) {
	rows, err := q.db.Query(ctx, listUomCategories,
		arg.TenantID,
		arg.After,
		arg.IncludeArchived,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UomCategory
	for rows.Next() {
		var i UomCategory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUomsByCategories = `-- name: ListUomsByCategories :many
SELECT id, tenant_id, category_id, name, is_reference, ratio_num, ratio_den, rounding_scaled, active, created_at, updated_at FROM uom WHERE tenant_id = $1 AND category_id = ANY($2::uuid[]) ORDER BY category_id, NOT is_reference, ratio_num::numeric / ratio_den, id
`

type ListUomsByCategoriesParams struct {
	TenantID    uuid.UUID
	CategoryIds []uuid.UUID
}

func (q *Queries) ListUomsByCategories(ctx context.Context, arg ListUomsByCategoriesParams) ([]Uom, error) {
	rows, err := q.db.Query(ctx, listUomsByCategories, arg.TenantID, arg.CategoryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Uom
	for rows.Next() {
		var i Uom
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.IsReference,
			&i.RatioNum,
			&i.RatioDen,
			&i.RoundingScaled,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredient
SET name = $1, category_id = $2, uom_id = $3, track = $4, description = $5, archived_at = $6
WHERE tenant_id = $7 AND id = $8
RETURNING id, tenant_id, name, category_id, uom_id, track, description, archived_at, created_at, updated_at
`

type UpdateIngredientParams struct {
	Name        string
	CategoryID  *uuid.UUID
	UomID       uuid.UUID
	Track       bool
	Description *string
	ArchivedAt  *time.Time
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.Name,
		arg.CategoryID,
		arg.UomID,
		arg.Track,
		arg.Description,
		arg.ArchivedAt,
		arg.TenantID,
		arg.ID,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CategoryID,
		&i.UomID,
		&i.Track,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIngredientCategory = `-- name: UpdateIngredientCategory :one
UPDATE ingredient_category
SET name = $1, default_transaction_type_id = $2, description = $3, archived_at = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, name, default_transaction_type_id, description, archived_at, created_at, updated_at
`

type UpdateIngredientCategoryParams struct {
	Name                     string
	DefaultTransactionTypeID *uuid.UUID
	Description              *string
	ArchivedAt               *time.Time
	TenantID                 uuid.UUID
	ID                       uuid.UUID
}

func (q *Queries) UpdateIngredientCategory(ctx context.Context, arg UpdateIngredientCategoryParams) (IngredientCategory, error) {
	row := q.db.QueryRow(ctx, updateIngredientCategory,
		arg.Name,
		arg.DefaultTransactionTypeID,
		arg.Description,
		arg.ArchivedAt,
		arg.TenantID,
		arg.ID,
	)
	var i IngredientCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DefaultTransactionTypeID,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionType = `-- name: UpdateTransactionType :one
UPDATE transaction_type SET name = $1, category = $2, description = $3, archived_at = $4
WHERE tenant_id = $5 AND id = $6
RETURNING id, tenant_id, name, category, description, archived_at, created_at, updated_at
`

type UpdateTransactionTypeParams struct {
	Name        string
	Category    string
	Description *string
	ArchivedAt  *time.Time
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateTransactionType(ctx context.Context, arg UpdateTransactionTypeParams) (TransactionType, error) {
	row := q.db.QueryRow(ctx, updateTransactionType,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.ArchivedAt,
		arg.TenantID,
		arg.ID,
	)
	var i TransactionType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUom = `-- name: UpdateUom :execrows
UPDATE uom SET name = $1, ratio_num = $2, ratio_den = $3, rounding_scaled = $4, active = $5
WHERE tenant_id = $6 AND category_id = $7 AND id = $8
`

type UpdateUomParams struct {
	Name           string
	RatioNum       int64
	RatioDen       int64
	RoundingScaled int64
	Active         bool
	TenantID       uuid.UUID
	CategoryID     uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) UpdateUom(ctx context.Context, arg UpdateUomParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUom,
		arg.Name,
		arg.RatioNum,
		arg.RatioDen,
		arg.RoundingScaled,
		arg.Active,
		arg.TenantID,
		arg.CategoryID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUomCategory = `-- name: UpdateUomCategory :one
UPDATE uom_category SET name = $1, archived_at = $2
WHERE tenant_id = $3 AND id = $4
RETURNING id, tenant_id, name, archived_at, created_at, updated_at
`

type UpdateUomCategoryParams struct {
	Name       string
	ArchivedAt *time.Time
	TenantID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateUomCategory(ctx context.Context, arg UpdateUomCategoryParams) (UomCategory, error) {
	row := q.db.QueryRow(ctx, updateUomCategory,
		arg.Name,
		arg.ArchivedAt,
		arg.TenantID,
		arg.ID,
	)
	var i UomCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
