// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getInboxByKey = `-- name: GetInboxByKey :one
SELECT tenant_id, device_id, idempotency_key, id, outlet_id, staff_id, event_type, schema_version, device_time, payload_hash, payload, status, code, detail, depends_on, received_at, applied_at FROM sync_inbox WHERE tenant_id = $1 AND device_id = $2 AND idempotency_key = $3
`

type GetInboxByKeyParams struct {
	TenantID       uuid.UUID
	DeviceID       uuid.UUID
	IdempotencyKey uuid.UUID
}

func (q *Queries) GetInboxByKey(ctx context.Context, arg GetInboxByKeyParams) (SyncInbox, error) {
	row := q.db.QueryRow(ctx, getInboxByKey, arg.TenantID, arg.DeviceID, arg.IdempotencyKey)
	var i SyncInbox
	err := row.Scan(
		&i.TenantID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.ID,
		&i.OutletID,
		&i.StaffID,
		&i.EventType,
		&i.SchemaVersion,
		&i.DeviceTime,
		&i.PayloadHash,
		&i.Payload,
		&i.Status,
		&i.Code,
		&i.Detail,
		&i.DependsOn,
		&i.ReceivedAt,
		&i.AppliedAt,
	)
	return i, err
}

const getInboxForUpdate = `-- name: GetInboxForUpdate :one
SELECT tenant_id, device_id, idempotency_key, id, outlet_id, staff_id, event_type, schema_version, device_time, payload_hash, payload, status, code, detail, depends_on, received_at, applied_at FROM sync_inbox WHERE tenant_id = $1 AND device_id = $2 AND idempotency_key = $3 FOR UPDATE
`

type GetInboxForUpdateParams struct {
	TenantID       uuid.UUID
	DeviceID       uuid.UUID
	IdempotencyKey uuid.UUID
}

func (q *Queries) GetInboxForUpdate(ctx context.Context, arg GetInboxForUpdateParams) (SyncInbox, error) {
	row := q.db.QueryRow(ctx, getInboxForUpdate, arg.TenantID, arg.DeviceID, arg.IdempotencyKey)
	var i SyncInbox
	err := row.Scan(
		&i.TenantID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.ID,
		&i.OutletID,
		&i.StaffID,
		&i.EventType,
		&i.SchemaVersion,
		&i.DeviceTime,
		&i.PayloadHash,
		&i.Payload,
		&i.Status,
		&i.Code,
		&i.Detail,
		&i.DependsOn,
		&i.ReceivedAt,
		&i.AppliedAt,
	)
	return i, err
}

const insertInbox = `-- name: InsertInbox :execrows
INSERT INTO sync_inbox (tenant_id, device_id, idempotency_key, id, outlet_id, staff_id, event_type, schema_version,
                        device_time, payload_hash, payload, status, received_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, 'received', $12)
ON CONFLICT DO NOTHING
`

type InsertInboxParams struct {
	TenantID       uuid.UUID
	DeviceID       uuid.UUID
	IdempotencyKey uuid.UUID
	ID             uuid.UUID
	OutletID       uuid.UUID
	StaffID        uuid.UUID
	EventType      string
	SchemaVersion  int32
	DeviceTime     time.Time
	PayloadHash    []byte
	Payload        []byte
	ReceivedAt     time.Time
}

// Does nothing when the event is already there (same device and key) or its id was used by another
// device; the caller reads the existing row to tell which. Zero rows means "already there".
func (q *Queries) InsertInbox(ctx context.Context, arg InsertInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInbox,
		arg.TenantID,
		arg.DeviceID,
		arg.IdempotencyKey,
		arg.ID,
		arg.OutletID,
		arg.StaffID,
		arg.EventType,
		arg.SchemaVersion,
		arg.DeviceTime,
		arg.PayloadHash,
		arg.Payload,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listParkedOn = `-- name: ListParkedOn :many
SELECT tenant_id, device_id, idempotency_key, id, outlet_id, staff_id, event_type, schema_version, device_time, payload_hash, payload, status, code, detail, depends_on, received_at, applied_at FROM sync_inbox
WHERE tenant_id = $1 AND status = 'pending_dependency' AND depends_on = ANY($2::uuid[])
ORDER BY received_at, id
FOR UPDATE
`

type ListParkedOnParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

// The events waiting for any of these records, oldest first, locked so two pushes cannot run the
// same one.
func (q *Queries) ListParkedOn(ctx context.Context, arg ListParkedOnParams) ([]SyncInbox, error) {
	rows, err := q.db.Query(ctx, listParkedOn, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncInbox
	for rows.Next() {
		var i SyncInbox
		if err := rows.Scan(
			&i.TenantID,
			&i.DeviceID,
			&i.IdempotencyKey,
			&i.ID,
			&i.OutletID,
			&i.StaffID,
			&i.EventType,
			&i.SchemaVersion,
			&i.DeviceTime,
			&i.PayloadHash,
			&i.Payload,
			&i.Status,
			&i.Code,
			&i.Detail,
			&i.DependsOn,
			&i.ReceivedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInboxOutcome = `-- name: SetInboxOutcome :exec
UPDATE sync_inbox
SET status = $1, code = $2, detail = $3, depends_on = $4,
    applied_at = $5
WHERE tenant_id = $6 AND device_id = $7 AND idempotency_key = $8
`

type SetInboxOutcomeParams struct {
	Status         string
	Code           *string
	Detail         *string
	DependsOn      *uuid.UUID
	AppliedAt      *time.Time
	TenantID       uuid.UUID
	DeviceID       uuid.UUID
	IdempotencyKey uuid.UUID
}

func (q *Queries) SetInboxOutcome(ctx context.Context, arg SetInboxOutcomeParams) error {
	_, err := q.db.Exec(ctx, setInboxOutcome,
		arg.Status,
		arg.Code,
		arg.Detail,
		arg.DependsOn,
		arg.AppliedAt,
		arg.TenantID,
		arg.DeviceID,
		arg.IdempotencyKey,
	)
	return err
}
