// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dayCashMovements = `-- name: DayCashMovements :many
SELECT kind, count(*)::bigint AS movements, coalesce(sum(amount), 0)::bigint AS amount
FROM cash_movement
WHERE tenant_id = $1 AND outlet_id = $2 AND business_date = $3
GROUP BY kind ORDER BY kind
`

type DayCashMovementsParams struct {
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	BusinessDate pgtype.Date
}

type DayCashMovementsRow struct {
	Kind      string
	Movements int64
	Amount    int64
}

func (q *Queries) DayCashMovements(ctx context.Context, arg DayCashMovementsParams) ([]DayCashMovementsRow, error) {
	rows, err := q.db.Query(ctx, dayCashMovements, arg.TenantID, arg.OutletID, arg.BusinessDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayCashMovementsRow
	for rows.Next() {
		var i DayCashMovementsRow
		if err := rows.Scan(&i.Kind, &i.Movements, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dayDiscounts = `-- name: DayDiscounts :one
SELECT count(*)::bigint AS discounts, coalesce(sum(d.amount), 0)::bigint AS amount
FROM sale sa JOIN sale_discount d ON d.tenant_id = sa.tenant_id AND d.sale_id = sa.id
WHERE sa.tenant_id = $1 AND sa.outlet_id = $2 AND sa.business_date = $3 AND sa.status = 'completed'
`

type DayDiscountsParams struct {
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	BusinessDate pgtype.Date
}

type DayDiscountsRow struct {
	Discounts int64
	Amount    int64
}

func (q *Queries) DayDiscounts(ctx context.Context, arg DayDiscountsParams) (DayDiscountsRow, error) {
	row := q.db.QueryRow(ctx, dayDiscounts, arg.TenantID, arg.OutletID, arg.BusinessDate)
	var i DayDiscountsRow
	err := row.Scan(&i.Discounts, &i.Amount)
	return i, err
}

const dayFlags = `-- name: DayFlags :many
SELECT f.code, count(*)::bigint AS flags
FROM flag f
WHERE f.tenant_id = $1 AND f.outlet_id = $2 AND (
       f.target_id IN (SELECT sa.id FROM sale sa WHERE sa.tenant_id = $1 AND sa.outlet_id = $2 AND sa.business_date = $3)
    OR f.target_id IN (SELECT v.id FROM void v WHERE v.tenant_id = $1 AND v.outlet_id = $2 AND v.business_date = $3)
    OR f.target_id IN (SELECT sh.id FROM shift sh WHERE sh.tenant_id = $1 AND sh.outlet_id = $2 AND sh.business_date = $3)
    OR f.target_id IN (SELECT m.id FROM cash_movement m WHERE m.tenant_id = $1 AND m.outlet_id = $2 AND m.business_date = $3))
GROUP BY f.code ORDER BY f.code
`

type DayFlagsParams struct {
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	BusinessDate pgtype.Date
}

type DayFlagsRow struct {
	Code  string
	Flags int64
}

// Flags raised about the day's sales, voids, shifts and cash movements, by code.
func (q *Queries) DayFlags(ctx context.Context, arg DayFlagsParams) ([]DayFlagsRow, error) {
	rows, err := q.db.Query(ctx, dayFlags, arg.TenantID, arg.OutletID, arg.BusinessDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayFlagsRow
	for rows.Next() {
		var i DayFlagsRow
		if err := rows.Scan(&i.Code, &i.Flags); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dayPaymentMethods = `-- name: DayPaymentMethods :many
SELECT p.method, count(*)::bigint AS payments, sum(p.amount)::bigint AS amount
FROM sale sa JOIN payment p ON p.tenant_id = sa.tenant_id AND p.sale_id = sa.id
WHERE sa.tenant_id = $1 AND sa.outlet_id = $2 AND sa.business_date = $3
  AND sa.status = 'completed' AND p.status = 'confirmed'
GROUP BY p.method ORDER BY p.method
`

type DayPaymentMethodsParams struct {
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	BusinessDate pgtype.Date
}

type DayPaymentMethodsRow struct {
	Method   string
	Payments int64
	Amount   int64
}

func (q *Queries) DayPaymentMethods(ctx context.Context, arg DayPaymentMethodsParams) ([]DayPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, dayPaymentMethods, arg.TenantID, arg.OutletID, arg.BusinessDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayPaymentMethodsRow
	for rows.Next() {
		var i DayPaymentMethodsRow
		if err := rows.Scan(&i.Method, &i.Payments, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const daySales = `-- name: DaySales :one
SELECT
    count(*) FILTER (WHERE status = 'completed')::bigint AS sales,
    coalesce(sum(subtotal) FILTER (WHERE status = 'completed'), 0)::bigint AS subtotal,
    coalesce(sum(discount_total) FILTER (WHERE status = 'completed'), 0)::bigint AS discount_total,
    coalesce(sum(service_charge) FILTER (WHERE status = 'completed'), 0)::bigint AS service_charge,
    coalesce(sum(tax) FILTER (WHERE status = 'completed'), 0)::bigint AS tax,
    coalesce(sum(rounding_amount) FILTER (WHERE status = 'completed'), 0)::bigint AS rounding,
    coalesce(sum(total) FILTER (WHERE status = 'completed'), 0)::bigint AS total,
    count(*) FILTER (WHERE status = 'voided')::bigint AS voided,
    coalesce(sum(total) FILTER (WHERE status = 'voided'), 0)::bigint AS voided_total
FROM sale WHERE tenant_id = $1 AND outlet_id = $2 AND business_date = $3
`

type DaySalesParams struct {
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	BusinessDate pgtype.Date
}

type DaySalesRow struct {
	Sales         int64
	Subtotal      int64
	DiscountTotal int64
	ServiceCharge int64
	Tax           int64
	Rounding      int64
	Total         int64
	Voided        int64
	VoidedTotal   int64
}

func (q *Queries) DaySales(ctx context.Context, arg DaySalesParams) (DaySalesRow, error) {
	row := q.db.QueryRow(ctx, daySales, arg.TenantID, arg.OutletID, arg.BusinessDate)
	var i DaySalesRow
	err := row.Scan(
		&i.Sales,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ServiceCharge,
		&i.Tax,
		&i.Rounding,
		&i.Total,
		&i.Voided,
		&i.VoidedTotal,
	)
	return i, err
}

const getShiftForReport = `-- name: GetShiftForReport :one

SELECT id, outlet_id, device_id, opened_by, opened_at, opening_cash, business_date, closed_by, closed_at, counted_cash
FROM shift WHERE tenant_id = $1 AND id = $2
`

type GetShiftForReportParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetShiftForReportRow struct {
	ID           uuid.UUID
	OutletID     uuid.UUID
	DeviceID     uuid.UUID
	OpenedBy     uuid.UUID
	OpenedAt     time.Time
	OpeningCash  int64
	BusinessDate pgtype.Date
	ClosedBy     *uuid.UUID
	ClosedAt     *time.Time
	CountedCash  *int64
}

// Reports read the sales tables and never write them. The columns they use are checked against the
// migrations when sqlc generates this code, so a schema change in sales that breaks a report fails
// the build.
func (q *Queries) GetShiftForReport(ctx context.Context, arg GetShiftForReportParams) (GetShiftForReportRow, error) {
	row := q.db.QueryRow(ctx, getShiftForReport, arg.TenantID, arg.ID)
	var i GetShiftForReportRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.DeviceID,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.OpeningCash,
		&i.BusinessDate,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CountedCash,
	)
	return i, err
}

const salesByDay = `-- name: SalesByDay :many

SELECT d::date AS business_date,
    count(sa.id)::bigint AS sales,
    coalesce(sum(sa.subtotal), 0)::bigint AS subtotal,
    coalesce(sum(sa.discount_total), 0)::bigint AS discount_total,
    coalesce(sum(sa.service_charge), 0)::bigint AS service_charge,
    coalesce(sum(sa.tax), 0)::bigint AS tax,
    coalesce(sum(sa.rounding_amount), 0)::bigint AS rounding,
    coalesce(sum(sa.total), 0)::bigint AS total
FROM generate_series($1::date, $2::date, interval '1 day') AS d
LEFT JOIN sale sa ON sa.tenant_id = $3 AND sa.outlet_id = $4 AND sa.business_date = d::date AND sa.status = 'completed'
GROUP BY d ORDER BY d
`

type SalesByDayParams struct {
	FromDate pgtype.Date
	ToDate   pgtype.Date
	TenantID uuid.UUID
	OutletID uuid.UUID
}

type SalesByDayRow struct {
	BusinessDate  pgtype.Date
	Sales         int64
	Subtotal      int64
	DiscountTotal int64
	ServiceCharge int64
	Tax           int64
	Rounding      int64
	Total         int64
}

// Sales over a range of business dates (B2.6). Completed sales only, as in the day report.
// Every date in the range, days without sales included.
func (q *Queries) SalesByDay(ctx context.Context, arg SalesByDayParams) ([]SalesByDayRow, error) {
	rows, err := q.db.Query(ctx, salesByDay,
		arg.FromDate,
		arg.ToDate,
		arg.TenantID,
		arg.OutletID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesByDayRow
	for rows.Next() {
		var i SalesByDayRow
		if err := rows.Scan(
			&i.BusinessDate,
			&i.Sales,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.ServiceCharge,
			&i.Tax,
			&i.Rounding,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByItem = `-- name: SalesByItem :many
SELECT l.variant_id, v.item_id, i.name AS item_name, v.name AS variant_name,
    sum(l.quantity)::bigint AS quantity,
    sum(l.line_total + l.line_discount + l.allocated_bill_discount)::bigint AS gross,
    sum(l.line_discount + l.allocated_bill_discount)::bigint AS discounts,
    sum(l.line_total)::bigint AS net
FROM sale sa
JOIN sale_line l ON l.tenant_id = sa.tenant_id AND l.sale_id = sa.id
JOIN variant v ON v.tenant_id = l.tenant_id AND v.id = l.variant_id
JOIN item i ON i.tenant_id = v.tenant_id AND i.id = v.item_id
WHERE sa.tenant_id = $1 AND sa.outlet_id = $2 AND sa.status = 'completed'
  AND sa.business_date BETWEEN $3::date AND $4::date
GROUP BY l.variant_id, v.item_id, i.name, v.name
ORDER BY net DESC, i.name, v.name, l.variant_id
`

type SalesByItemParams struct {
	TenantID uuid.UUID
	OutletID uuid.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type SalesByItemRow struct {
	VariantID   uuid.UUID
	ItemID      uuid.UUID
	ItemName    string
	VariantName string
	Quantity    int64
	Gross       int64
	Discounts   int64
	Net         int64
}

// Per variant sold, named as in the catalog now. A line's total is its gross less its own discount
// and its share of the bill discount, so the rows' net adds up to the sales' net.
func (q *Queries) SalesByItem(ctx context.Context, arg SalesByItemParams) ([]SalesByItemRow, error) {
	rows, err := q.db.Query(ctx, salesByItem,
		arg.TenantID,
		arg.OutletID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesByItemRow
	for rows.Next() {
		var i SalesByItemRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ItemID,
			&i.ItemName,
			&i.VariantName,
			&i.Quantity,
			&i.Gross,
			&i.Discounts,
			&i.Net,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByPaymentMethod = `-- name: SalesByPaymentMethod :many
SELECT p.method, count(*)::bigint AS payments, sum(p.amount)::bigint AS amount
FROM sale sa JOIN payment p ON p.tenant_id = sa.tenant_id AND p.sale_id = sa.id
WHERE sa.tenant_id = $1 AND sa.outlet_id = $2 AND sa.status = 'completed' AND p.status = 'confirmed'
  AND sa.business_date BETWEEN $3::date AND $4::date
GROUP BY p.method ORDER BY p.method
`

type SalesByPaymentMethodParams struct {
	TenantID uuid.UUID
	OutletID uuid.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type SalesByPaymentMethodRow struct {
	Method   string
	Payments int64
	Amount   int64
}

func (q *Queries) SalesByPaymentMethod(ctx context.Context, arg SalesByPaymentMethodParams) ([]SalesByPaymentMethodRow, error) {
	rows, err := q.db.Query(ctx, salesByPaymentMethod,
		arg.TenantID,
		arg.OutletID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesByPaymentMethodRow
	for rows.Next() {
		var i SalesByPaymentMethodRow
		if err := rows.Scan(&i.Method, &i.Payments, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shiftCash = `-- name: ShiftCash :many
SELECT s.id AS shift_id,
    coalesce((SELECT sum(p.amount) FROM sale sa JOIN payment p ON p.tenant_id = sa.tenant_id AND p.sale_id = sa.id
              WHERE sa.tenant_id = s.tenant_id AND sa.shift_id = s.id AND p.method = 'cash' AND p.status = 'confirmed'), 0)::bigint AS received,
    coalesce((SELECT sum(p.amount) FROM void v JOIN payment p ON p.tenant_id = v.tenant_id AND p.sale_id = v.sale_id
              WHERE v.tenant_id = s.tenant_id AND v.shift_id = s.id AND p.method = 'cash' AND p.status = 'confirmed'), 0)::bigint AS refunded,
    coalesce((SELECT sum(m.amount) FROM cash_movement m WHERE m.tenant_id = s.tenant_id AND m.shift_id = s.id AND m.kind = 'pay_in'), 0)::bigint AS pay_in,
    coalesce((SELECT sum(m.amount) FROM cash_movement m WHERE m.tenant_id = s.tenant_id AND m.shift_id = s.id AND m.kind = 'pay_out'), 0)::bigint AS pay_out,
    (SELECT count(*) FROM cash_movement m WHERE m.tenant_id = s.tenant_id AND m.shift_id = s.id AND m.kind = 'no_sale')::bigint AS no_sales
FROM shift s
WHERE s.tenant_id = $1 AND s.id = ANY($2::uuid[])
`

type ShiftCashParams struct {
	TenantID uuid.UUID
	ShiftIds []uuid.UUID
}

type ShiftCashRow struct {
	ShiftID  uuid.UUID
	Received int64
	Refunded int64
	PayIn    int64
	PayOut   int64
	NoSales  int64
}

// The cash that moved through each shift's drawer, for many shifts at once.
//
//	received: cash applied to the bills of sales rung up in the shift (net of change given), whatever
//	          became of the sale later;
//	refunded: cash returned for sales voided in this shift, whichever shift sold them;
//	pay in, pay out, and how many times the drawer was opened without a sale.
func (q *Queries) ShiftCash(ctx context.Context, arg ShiftCashParams) ([]ShiftCashRow, error) {
	rows, err := q.db.Query(ctx, shiftCash, arg.TenantID, arg.ShiftIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftCashRow
	for rows.Next() {
		var i ShiftCashRow
		if err := rows.Scan(
			&i.ShiftID,
			&i.Received,
			&i.Refunded,
			&i.PayIn,
			&i.PayOut,
			&i.NoSales,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shiftDiscounts = `-- name: ShiftDiscounts :one
SELECT count(*)::bigint AS discounts, coalesce(sum(d.amount), 0)::bigint AS amount
FROM sale sa JOIN sale_discount d ON d.tenant_id = sa.tenant_id AND d.sale_id = sa.id
WHERE sa.tenant_id = $1 AND sa.shift_id = $2 AND sa.status = 'completed'
`

type ShiftDiscountsParams struct {
	TenantID uuid.UUID
	ShiftID  uuid.UUID
}

type ShiftDiscountsRow struct {
	Discounts int64
	Amount    int64
}

func (q *Queries) ShiftDiscounts(ctx context.Context, arg ShiftDiscountsParams) (ShiftDiscountsRow, error) {
	row := q.db.QueryRow(ctx, shiftDiscounts, arg.TenantID, arg.ShiftID)
	var i ShiftDiscountsRow
	err := row.Scan(&i.Discounts, &i.Amount)
	return i, err
}

const shiftFlagCount = `-- name: ShiftFlagCount :one
SELECT count(*)::bigint FROM flag f
WHERE f.tenant_id = $1 AND (f.target_id = $2 OR f.target_id IN (SELECT sa.id FROM sale sa WHERE sa.tenant_id = $1 AND sa.shift_id = $2))
`

type ShiftFlagCountParams struct {
	TenantID uuid.UUID
	ShiftID  uuid.UUID
}

func (q *Queries) ShiftFlagCount(ctx context.Context, arg ShiftFlagCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, shiftFlagCount, arg.TenantID, arg.ShiftID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const shiftPaymentMethods = `-- name: ShiftPaymentMethods :many
SELECT p.method, count(*)::bigint AS payments, sum(p.amount)::bigint AS amount
FROM sale sa JOIN payment p ON p.tenant_id = sa.tenant_id AND p.sale_id = sa.id
WHERE sa.tenant_id = $1 AND sa.shift_id = $2 AND sa.status = 'completed' AND p.status = 'confirmed'
GROUP BY p.method ORDER BY p.method
`

type ShiftPaymentMethodsParams struct {
	TenantID uuid.UUID
	ShiftID  uuid.UUID
}

type ShiftPaymentMethodsRow struct {
	Method   string
	Payments int64
	Amount   int64
}

func (q *Queries) ShiftPaymentMethods(ctx context.Context, arg ShiftPaymentMethodsParams) ([]ShiftPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, shiftPaymentMethods, arg.TenantID, arg.ShiftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftPaymentMethodsRow
	for rows.Next() {
		var i ShiftPaymentMethodsRow
		if err := rows.Scan(&i.Method, &i.Payments, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shiftSales = `-- name: ShiftSales :one
SELECT
    count(*) FILTER (WHERE status = 'completed')::bigint AS sales,
    coalesce(sum(subtotal) FILTER (WHERE status = 'completed'), 0)::bigint AS subtotal,
    coalesce(sum(discount_total) FILTER (WHERE status = 'completed'), 0)::bigint AS discount_total,
    coalesce(sum(service_charge) FILTER (WHERE status = 'completed'), 0)::bigint AS service_charge,
    coalesce(sum(tax) FILTER (WHERE status = 'completed'), 0)::bigint AS tax,
    coalesce(sum(rounding_amount) FILTER (WHERE status = 'completed'), 0)::bigint AS rounding,
    coalesce(sum(total) FILTER (WHERE status = 'completed'), 0)::bigint AS total,
    count(*) FILTER (WHERE status = 'voided')::bigint AS voided,
    coalesce(sum(total) FILTER (WHERE status = 'voided'), 0)::bigint AS voided_total
FROM sale WHERE tenant_id = $1 AND shift_id = $2
`

type ShiftSalesParams struct {
	TenantID uuid.UUID
	ShiftID  uuid.UUID
}

type ShiftSalesRow struct {
	Sales         int64
	Subtotal      int64
	DiscountTotal int64
	ServiceCharge int64
	Tax           int64
	Rounding      int64
	Total         int64
	Voided        int64
	VoidedTotal   int64
}

// Completed sales of one shift, and the sales of it that were voided.
func (q *Queries) ShiftSales(ctx context.Context, arg ShiftSalesParams) (ShiftSalesRow, error) {
	row := q.db.QueryRow(ctx, shiftSales, arg.TenantID, arg.ShiftID)
	var i ShiftSalesRow
	err := row.Scan(
		&i.Sales,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ServiceCharge,
		&i.Tax,
		&i.Rounding,
		&i.Total,
		&i.Voided,
		&i.VoidedTotal,
	)
	return i, err
}

const shiftVoidsRecorded = `-- name: ShiftVoidsRecorded :one
SELECT count(*)::bigint AS voids, coalesce(sum(sa.total), 0)::bigint AS total
FROM void v JOIN sale sa ON sa.tenant_id = v.tenant_id AND sa.id = v.sale_id
WHERE v.tenant_id = $1 AND v.shift_id = $2
`

type ShiftVoidsRecordedParams struct {
	TenantID uuid.UUID
	ShiftID  uuid.UUID
}

type ShiftVoidsRecordedRow struct {
	Voids int64
	Total int64
}

// Voids made during the shift, and what they refunded, whichever shift sold the sale.
func (q *Queries) ShiftVoidsRecorded(ctx context.Context, arg ShiftVoidsRecordedParams) (ShiftVoidsRecordedRow, error) {
	row := q.db.QueryRow(ctx, shiftVoidsRecorded, arg.TenantID, arg.ShiftID)
	var i ShiftVoidsRecordedRow
	err := row.Scan(&i.Voids, &i.Total)
	return i, err
}

const shiftsOfDay = `-- name: ShiftsOfDay :many
SELECT id, outlet_id, device_id, opened_by, opened_at, opening_cash, business_date, closed_by, closed_at, counted_cash
FROM shift
WHERE tenant_id = $1 AND outlet_id = $2 AND business_date = $3
ORDER BY opened_at, id
`

type ShiftsOfDayParams struct {
	TenantID     uuid.UUID
	OutletID     uuid.UUID
	BusinessDate pgtype.Date
}

type ShiftsOfDayRow struct {
	ID           uuid.UUID
	OutletID     uuid.UUID
	DeviceID     uuid.UUID
	OpenedBy     uuid.UUID
	OpenedAt     time.Time
	OpeningCash  int64
	BusinessDate pgtype.Date
	ClosedBy     *uuid.UUID
	ClosedAt     *time.Time
	CountedCash  *int64
}

func (q *Queries) ShiftsOfDay(ctx context.Context, arg ShiftsOfDayParams) ([]ShiftsOfDayRow, error) {
	rows, err := q.db.Query(ctx, shiftsOfDay, arg.TenantID, arg.OutletID, arg.BusinessDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShiftsOfDayRow
	for rows.Next() {
		var i ShiftsOfDayRow
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.DeviceID,
			&i.OpenedBy,
			&i.OpenedAt,
			&i.OpeningCash,
			&i.BusinessDate,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.CountedCash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
